"""Structural protocols for SPECTRAX-GK extension points.

The protocols are intentionally structural and dependency-light. Collision
operators are active in cached RHS and explicit state-integration paths; the
remaining protocols define the narrow interfaces used as other domains become
pluggable.
"""

from __future__ import annotations

from typing import Any, NamedTuple, Protocol, runtime_checkable


@runtime_checkable
class BasisFamily(Protocol):
    """Orthogonal velocity-space basis family used by moment-space operators."""

    def recurrence_coefficients(self, order: int) -> Any:
        """Return recurrence data for the requested polynomial order."""


@runtime_checkable
class GeometryProvider(Protocol):
    """Provider that maps equilibrium parameters to sampled flux-tube geometry."""

    def sample_flux_tube(self, parameters: Any) -> Any:
        """Return a solver-ready sampled flux-tube geometry object."""


class CollisionContext(NamedTuple):
    """Post-field state needed by a gyrokinetic collision operator.

    ``distribution`` is the evolved :math:`G` state, while ``hamiltonian`` is
    the corresponding :math:`H` response after the field solve. Keeping both
    arrays explicit prevents finite-Larmor-radius and field-particle models
    from silently applying a long-wavelength approximation.
    """

    distribution: Any
    hamiltonian: Any
    fields: Any
    cache: Any
    parameters: Any


@runtime_checkable
class CollisionOperator(Protocol):
    """JAX-compatible unit-weight gyrokinetic collision model."""

    def apply(self, context: CollisionContext) -> Any:
        """Return a collision RHS contribution with the same state layout."""


@runtime_checkable
class SplitCollisionOperator(CollisionOperator, Protocol):
    """Collision model with a mathematically valid finite-time update."""

    def split_step(self, context: CollisionContext, dt: Any) -> Any:
        """Advance the unit-weight collision model by ``dt``."""


@runtime_checkable
class FieldSolver(Protocol):
    """Field-equation solver for potential and electromagnetic response fields."""

    def solve_fields(self, distribution: Any, geometry: Any, parameters: Any) -> Any:
        """Return fields generated by a distribution in a sampled geometry."""


@runtime_checkable
class LinearRHS(Protocol):
    """Linear right-hand side callable with explicit time, state, and parameters."""

    def __call__(self, time: Any, state: Any, parameters: Any) -> Any:
        """Return the linear time derivative for ``state``."""


@runtime_checkable
class NonlinearRHS(Protocol):
    """Nonlinear right-hand side callable with explicit time, state, and parameters."""

    def __call__(self, time: Any, state: Any, parameters: Any) -> Any:
        """Return the nonlinear time derivative for ``state``."""


@runtime_checkable
class Diagnostic(Protocol):
    """Observable extractor used by runtime, validation, and plotting workflows."""

    def evaluate(self, state: Any, fields: Any, geometry: Any, parameters: Any) -> Any:
        """Return diagnostic values for a sampled state and fields."""


@runtime_checkable
class Objective(Protocol):
    """Differentiable or derivative-free objective used by optimization workflows."""

    def evaluate(self, parameters: Any) -> Any:
        """Return scalar or vector objective values for optimizer parameters."""


@runtime_checkable
class ArtifactWriter(Protocol):
    """Side-effectful writer kept outside differentiable objective functions."""

    def write(self, payload: Any, destination: Any) -> Any:
        """Persist ``payload`` to ``destination`` and return writer metadata."""
