"""Domain-organized public API registry for SPECTRAX-GK."""

from __future__ import annotations

import ast
from importlib import import_module
from pathlib import Path
from typing import Any

_API_MODULE_ORDER = (
    "configuration",
    "geometry",
    "diagnostics",
    "runtime",
    "solvers",
    "benchmarks",
    "validation",
    "parallel",
    "objectives",
    "artifacts",
)


__all__ = [
    "CycloneBaseCase",
    "ETGBaseCase",
    "GridConfig",
    "KineticElectronBaseCase",
    "KBMBaseCase",
    "TEMBaseCase",
    "TimeConfig",
    "SAlphaGeometry",
    "build_flux_tube_geometry",
    "booz_xform_flux_tube_mapping_from_inputs",
    "booz_xform_flux_tube_sensitivity_report",
    "booz_xform_spectral_sensitivity_report",
    "discover_differentiable_geometry_backends",
    "evaluate_boozer_bmag_on_field_line",
    "finite_difference_jacobian",
    "flux_tube_geometry_from_mapping",
    "flux_tube_geometry_from_vmec_boozer_state",
    "flux_tube_geometry_observables",
    "geometry_inverse_design_report",
    "geometry_observable_names",
    "geometry_sensitivity_report",
    "vmec_jax_boozer_equal_arc_core_profiles_from_state",
    "vmec_jax_boozer_flux_tube_sensitivity_report",
    "vmec_jax_field_line_tensor_sensitivity_report",
    "vmec_jax_flux_tube_array_parity_report",
    "vmec_jax_flux_tube_mapping_from_state",
    "vmec_jax_flux_tube_sensitivity_report",
    "vmec_jax_metric_tensor_sensitivity_report",
    "vmec_boundary_aspect_sensitivity_report",
    "vmec_field_line_tensor_observable_names",
    "vmec_metric_tensor_observable_names",
    "J_l_all",
    "gamma0",
    "load_case_from_toml",
    "load_krylov_from_toml",
    "load_linear_terms_from_toml",
    "load_runtime_from_toml",
    "DiagnosticNorm",
    "NormalizationContract",
    "get_normalization_contract",
    "apply_diagnostic_normalization",
    "RuntimeConfig",
    "RuntimeSpeciesConfig",
    "RuntimePhysicsConfig",
    "RuntimeCollisionConfig",
    "RuntimeNormalizationConfig",
    "RuntimeOutputConfig",
    "RuntimeParallelConfig",
    "RuntimeQuasilinearConfig",
    "RuntimeTermsConfig",
    "QuasilinearTransportResult",
    "compute_quasilinear_from_linear_state",
    "effective_kperp2",
    "mixing_length_amplitude2_jax",
    "phi_norm2",
    "quasilinear_feature_objective",
    "saturation_amplitude2",
    "saturated_flux_from_linear_weight",
    "shape_aware_power_law_objective",
    "QuasilinearCalibrationPoint",
    "apply_heat_flux_scale",
    "calibration_point_from_nonlinear_window_summary",
    "calibration_point_from_spectrum_and_nonlinear_window",
    "fit_train_heat_flux_scale",
    "integrated_quasilinear_flux_from_spectrum",
    "quasilinear_calibration_report",
    "write_quasilinear_calibration_report",
    "build_quasilinear_model_selection_status",
    "build_quasilinear_model_selection_status_from_paths",
    "NonlinearWindowConvergenceConfig",
    "NonlinearWindowEnsembleConfig",
    "NonlinearWindowEnsembleManifestConfig",
    "nonlinear_window_convergence_from_csv",
    "nonlinear_window_convergence_from_summary",
    "nonlinear_window_convergence_report",
    "nonlinear_window_ensemble_artifact_manifest",
    "nonlinear_window_ensemble_report",
    "nonlinear_window_stats_promotion_ready",
    "ProductionNonlinearOptimizationGuardConfig",
    "matched_optimized_transport_report",
    "optimized_equilibrium_transport_report",
    "production_nonlinear_optimization_guard_report",
    "reduced_artifact_scope_report",
    "replicated_transport_ensemble_report",
    "RuntimeLinearResult",
    "RuntimeLinearScanResult",
    "build_runtime_linear_params",
    "build_runtime_linear_terms",
    "build_runtime_term_config",
    "run_linear_case",
    "run_nonlinear_case",
    "run_runtime_linear",
    "run_runtime_nonlinear",
    "run_runtime_scan",
    "hermite_streaming",
    "LinearParams",
    "LinearTerms",
    "LinearCache",
    "build_linear_cache",
    "linear_terms_to_term_config",
    "term_config_to_linear_terms",
    "linear_rhs",
    "linear_rhs_cached",
    "linear_rhs_electrostatic_slices_velocity_sharded",
    "linear_rhs_streaming_electrostatic_velocity_sharded",
    "linear_rhs_parallel_cached",
    "linear_rhs_streaming_velocity_sharded",
    "integrate_linear",
    "KrylovConfig",
    "dominant_eigenpair",
    "dominant_eigenvalue",
    "integrate_linear_diffrax",
    "integrate_linear_diffrax_streaming",
    "integrate_linear_sharded",
    "integrate_nonlinear_sharded",
    "integrate_nonlinear",
    "integrate_nonlinear_cached",
    "integrate_nonlinear_explicit_diagnostics",
    "integrate_nonlinear_diagnostics",
    "integrate_nonlinear_diffrax",
    "build_nonlinear_imex_operator",
    "IMEXLinearOperator",
    "ExplicitTimeConfig",
    "LinearExplicitTimeConfig",
    "integrate_linear_explicit",
    "integrate_linear_explicit_diagnostics",
    "SimulationDiagnostics",
    "nonlinear_rhs_cached",
    "integrate_linear_from_config",
    "integrate_nonlinear_from_config",
    "Species",
    "build_linear_params",
    "load_cyclone_reference",
    "load_cyclone_reference_kinetic",
    "load_etg_reference",
    "load_kbm_reference",
    "load_tem_reference",
    "fit_growth_rate",
    "fit_growth_rate_auto",
    "instantaneous_growth_rate_from_phi",
    "growth_rate_from_phi",
    "select_fit_window",
    "CycloneReference",
    "CycloneScanResult",
    "CycloneComparison",
    "LinearRunResult",
    "LinearScanResult",
    "run_etg_linear",
    "run_etg_scan",
    "run_kinetic_linear",
    "run_kinetic_scan",
    "run_tem_linear",
    "run_tem_scan",
    "run_kbm_beta_scan",
    "run_kbm_scan",
    "run_cyclone_linear",
    "run_cyclone_scan",
    "ScanAndModeResult",
    "BranchContinuationMetrics",
    "ScalarGateResult",
    "GateReport",
    "LateTimeLinearMetrics",
    "NonlinearWindowMetrics",
    "ZonalFlowResponseMetrics",
    "branch_continuity_gate_report",
    "branch_continuity_metrics",
    "covariance_diagnostics",
    "autodiff_finite_difference_report",
    "central_finite_difference_jacobian",
    "explicit_complex_operator_matrix",
    "implicit_eigenpair_observable_sensitivity_report",
    "isolated_eigenpair_observable_sensitivity_report",
    "isolated_eigenvalue_sensitivity_report",
    "IndependentEnsembleProvenanceReport",
    "IndependentMapExecutionError",
    "IndependentWorkerMetadata",
    "ParallelIdentityReport",
    "batch_map",
    "batch_map_identity_report",
    "independent_ensemble_provenance_gate",
    "independent_map",
    "independent_map_identity_report",
    "independent_worker_metadata",
    "ky_scan_batches",
    "parallel_identity_report",
    "DecompositionContract",
    "ReconstructionIdentityReport",
    "ShardAssignment",
    "build_diagnostic_nonlinear_domain_decomposition",
    "build_independent_portfolio_decomposition",
    "reconstruct_serial",
    "serial_reconstruction_identity_report",
    "shard_sequence",
    "NonlinearDomainDecompositionPlan",
    "NonlinearDomainIdentityReport",
    "NonlinearDomainTransportWindowReport",
    "NonlinearParallelStrategy",
    "NonlinearSpectralCommunicationReport",
    "NonlinearSpectralDevicePencilFFTBatchModel",
    "NonlinearSpectralDevicePencilRHSIdentityReport",
    "NonlinearSpectralDevicePencilTransportWindowReport",
    "NonlinearSpectralDomainWorkModel",
    "NonlinearSpectralIntegratorIdentityReport",
    "NonlinearSpectralPencilRHSIdentityReport",
    "NonlinearSpectralPencilTransportWindowReport",
    "NonlinearSpectralPencilWorkModel",
    "NonlinearSpectralRHSIdentityReport",
    "build_nonlinear_domain_decomposition_plan",
    "classify_nonlinear_parallel_strategy",
    "deterministic_nonlinear_domain_state",
    "deterministic_nonlinear_spectral_state",
    "device_z_pencil_fft_batch_pressure_model",
    "device_z_pencil_nonlinear_spectral_rhs",
    "device_z_pencil_nonlinear_spectral_transport_window_identity_gate",
    "integrate_logical_decomposed_nonlinear_spectral",
    "nonlinear_domain_identity_report",
    "nonlinear_domain_parallel_identity_gate",
    "nonlinear_domain_transport_window_identity_gate",
    "nonlinear_parallel_strategies",
    "nonlinear_parallel_strategy",
    "nonlinear_spectral_communication_identity_gate",
    "nonlinear_spectral_communication_identity_report",
    "nonlinear_spectral_domain_work_model",
    "logical_decomposed_nonlinear_spectral_rhs",
    "nonlinear_spectral_integrator_identity_gate",
    "nonlinear_spectral_pencil_rhs_identity_gate",
    "nonlinear_spectral_pencil_transport_window_identity_gate",
    "nonlinear_spectral_pencil_work_model",
    "nonlinear_spectral_rhs_identity_gate",
    "nonlinear_spectral_rhs_identity_report",
    "pencil_decomposed_nonlinear_spectral_rhs",
    "local_stencil_nonlinear_domain_decomposed_step",
    "local_stencil_nonlinear_domain_serial_step",
    "release_ready_nonlinear_parallel_strategies",
    "VelocityShardingPlan",
    "build_velocity_sharding_plan",
    "curvature_gradb_drift_reference",
    "curvature_gradb_drift_shard_map",
    "diamagnetic_drive_reference",
    "diamagnetic_drive_shard_map",
    "electrostatic_phi_reference",
    "electrostatic_phi_shard_map",
    "hermite_neighbor_reference",
    "hermite_neighbor_shard_map",
    "hermite_shift_reference",
    "hermite_shift_shard_map",
    "hermite_streaming_ladder_reference",
    "hermite_streaming_ladder_shard_map",
    "mirror_drift_reference",
    "mirror_drift_shard_map",
    "periodic_streaming_reference",
    "periodic_streaming_shard_map",
    "velocity_field_reduce_reference",
    "velocity_field_reduce_shard_map",
    "QA_LOW_TURBULENCE_DESIGN_NAMES",
    "QA_LOW_TURBULENCE_OBSERVABLE_NAMES",
    "QALowTurbulenceConfig",
    "QALowTurbulenceResult",
    "default_qa_low_turbulence_initial_params",
    "optimize_qa_low_turbulence",
    "qa_low_turbulence_comparison_payload",
    "qa_low_turbulence_heat_flux_trace",
    "qa_low_turbulence_observable_sensitivity_report",
    "qa_low_turbulence_window_metrics",
    "qa_low_turbulence_observable_vector",
    "qa_low_turbulence_observables",
    "qa_low_turbulence_objective",
    "qa_low_turbulence_residual_names",
    "qa_low_turbulence_residual_vector",
    "reduced_boundary_surface",
    "reduced_lcfs_bmag",
    "STELLARATOR_ITG_OBSERVABLE_NAMES",
    "STELLARATOR_ITG_PARAMETER_NAMES",
    "StellaratorITGOptimizationConfig",
    "StellaratorITGOptimizationResult",
    "StellaratorITGSampleSet",
    "StellaratorObjectiveKind",
    "compare_stellarator_itg_objectives",
    "default_stellarator_initial_params",
    "nonlinear_heat_flux_trace",
    "nonlinear_heat_flux_window_metrics",
    "optimize_stellarator_itg",
    "qa_max_mode1_observables",
    "qa_observable_vector",
    "stellarator_itg_density_gradient_scan",
    "stellarator_itg_portfolio_gate_payload",
    "stellarator_itg_portfolio_sensitivity_report",
    "stellarator_itg_objective",
    "stellarator_itg_objective_residual_names",
    "stellarator_itg_objective_residual_vector",
    "stellarator_itg_reduced_portfolio_objective",
    "stellarator_itg_residual_sensitivity_report",
    "stellarator_itg_sample_objective_table",
    "stellarator_itg_vmec_boozer_portfolio_objective_from_state",
    "stellarator_itg_vmec_boozer_sample_objective_table_from_state",
    "StellaratorObjectivePortfolioContract",
    "ReducedPortfolioArtifactGuardConfig",
    "ProjectedLineSearchPolicy",
    "VMECJAXSpectraxTransportObjective",
    "VMECJAXTransportObjectiveConfig",
    "VMECJAXTransportObjectiveKind",
    "VMECJAXNonlinearAuditPolicy",
    "VMECJAXNonlinearCampaignPolicy",
    "VMECJAXReducedPrelaunchPolicy",
    "VMECJAXTransportAdmissionPolicy",
    "DEFAULT_TRANSPORT_METRIC_KEYS",
    "aggregate_objective_portfolio",
    "build_authoritative_wout_candidate_gate",
    "build_solved_vmec_candidate_gate",
    "build_wout_reproducibility_gate",
    "build_nonlinear_campaign_admission_report",
    "build_nonlinear_landscape_admission_report",
    "build_nonlinear_audit_redesign_report",
    "build_reduced_nonlinear_audit_prelaunch_report",
    "build_transport_admission_report",
    "boundary_spec_record",
    "boundary_chain_accepted_parameter_indices",
    "boundary_chain_summary_from_probe",
    "build_boundary_chain_collection_summary",
    "build_boundary_chain_summary",
    "candidate_transport_metric",
    "final_iota_profiles_from_vmec_result",
    "objective_portfolio_sensitivity_report",
    "portfolio_objective_weight_vector",
    "portfolio_sample_weight_tensor",
    "projected_line_search_input_manifest",
    "reduced_portfolio_artifact_guard_report",
    "validate_objective_portfolio_contract",
    "ZONAL_FLOW_OBJECTIVE_NAMES",
    "ZonalFlowObjectiveConfig",
    "zonal_flow_objective_artifact_from_records",
    "zonal_flow_objective_rows",
    "zonal_flow_objective_sensitivity_report",
    "zonal_flow_reduced_objective",
    "SOLVER_GEOMETRY_PARAMETER_NAMES",
    "SOLVER_OBJECTIVE_NAMES",
    "SolverScalarObjective",
    "VMEC_BOOZER_FREQUENCY_OBJECTIVE_NAMES",
    "VMEC_BOOZER_NONLINEAR_WINDOW_OBJECTIVE_NAMES",
    "VMEC_BOOZER_QUASILINEAR_OBJECTIVE_NAMES",
    "VMEC_BOOZER_STATE_PARAMETER_FAMILIES",
    "VMEC_BOOZER_STATE_PARAMETER_NAMES",
    "default_solver_geometry_design_params",
    "dominant_eigenvalue_branch_locality_report",
    "dominant_real_eigenvalue",
    "linear_solver_geometry_gradient_report",
    "mode21_vmec_boozer_linear_frequency_gradient_report",
    "mode21_vmec_boozer_nonlinear_window_gradient_report",
    "mode21_vmec_boozer_quasilinear_gradient_report",
    "solver_linear_operator_matrix_from_geometry",
    "solver_objective_branch_gradient_report",
    "solver_growth_rate_from_geometry",
    "solver_objective_vector_from_geometry",
    "solver_grid_options_from_ky_values",
    "solver_scalar_objective_from_vector",
    "spectrax_transport_objective_tuple",
    "select_admitted_transport_candidate",
    "transport_objective_sample_summary",
    "build_boundary_transport_gradient_report",
    "select_projected_line_search_candidate",
    "sparse_descent_direction_from_gradient_report",
    "vmec_jax_transport_growth_branch_locality_report_from_states",
    "vmec_jax_transport_objective_from_state",
    "write_boundary_transport_gradient_report",
    "solver_ready_geometry_mapping",
    "vmec_boozer_aggregate_line_search_holdout_report",
    "vmec_boozer_aggregate_scalar_objective_finite_difference_report",
    "vmec_boozer_aggregate_scalar_objective_from_state",
    "vmec_boozer_aggregate_scalar_objective_line_search_report",
    "vmec_boozer_scalar_objective_finite_difference_report",
    "vmec_boozer_scalar_objective_from_state",
    "vmec_boozer_scalar_objective_line_search_report",
    "vmec_boozer_solver_objective_table_from_state",
    "vmec_boozer_solver_objective_table_with_metadata_from_state",
    "vmec_boozer_solver_objective_vector_from_state",
    "eigenfunction_gate_report",
    "evaluate_scalar_gate",
    "gate_report",
    "gate_report_to_dict",
    "linear_metrics_gate_report",
    "nonlinear_window_gate_report",
    "observed_order_gate_report",
    "zonal_response_gate_report",
    "normalize_eigenfunction",
    "run_linear_scan",
    "run_scan_and_mode",
    "compare_cyclone_to_reference",
    "CycloneRunResult",
    "ModeSelection",
    "extract_mode",
    "extract_mode_time_series",
    "extract_eigenfunction",
    "select_ky_index",
    "cyclone_reference_figure",
    "cyclone_comparison_figure",
    "etg_trend_figure",
    "growth_rate_heatmap",
    "growth_fit_figure",
    "linear_validation_figure",
    "LinearValidationPanel",
    "MultiReferenceValidationPanel",
    "ReferenceSeries",
    "linear_validation_multi_reference_figure",
    "scan_multi_reference_figure",
    "scan_comparison_figure",
    "set_plot_style",
]


def _literal_all(path: Path) -> list[str]:
    """Read a grouped API module's export list without importing it."""

    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(
            isinstance(target, ast.Name) and target.id == "__all__"
            for target in node.targets
        ):
            names = ast.literal_eval(node.value)
            return [str(name) for name in names]
    raise RuntimeError(f"{path} does not define a literal __all__")


def _api_export_modules() -> dict[str, str]:
    api_dir = Path(__file__).parent
    export_modules: dict[str, str] = {}
    for module_name in _API_MODULE_ORDER:
        for name in _literal_all(api_dir / f"{module_name}.py"):
            export_modules.setdefault(name, module_name)
    missing = [name for name in __all__ if name not in export_modules]
    if missing:
        joined = ", ".join(missing)
        raise RuntimeError(
            f"public API export(s) are missing from API modules: {joined}"
        )
    return export_modules


_EXPORT_MODULES = _api_export_modules()


def __getattr__(name: str) -> Any:
    """Lazily resolve grouped public API exports."""

    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f"spectraxgk.api.{module_name}")
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
