"""Lazy public API registry for SPECTRAX-GK.

The runtime package keeps physics, numerics, diagnostics, and workflow
ownership in their domain modules. This facade provides a compact public
import surface without keeping one re-export module per domain.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    'CycloneBaseCase',
    'GridConfig',
    'KineticElectronBaseCase',
    'KBMBaseCase',
    'TEMBaseCase',
    'TimeConfig',
    'SAlphaGeometry',
    'build_flux_tube_geometry',
    'booz_xform_flux_tube_mapping_from_inputs',
    'booz_xform_flux_tube_sensitivity_report',
    'booz_xform_spectral_sensitivity_report',
    'discover_differentiable_geometry_backends',
    'evaluate_boozer_bmag_on_field_line',
    'finite_difference_jacobian',
    'flux_tube_geometry_from_mapping',
    'flux_tube_geometry_from_vmec_boozer_state',
    'flux_tube_geometry_observables',
    'geometry_inverse_design_report',
    'geometry_observable_names',
    'geometry_sensitivity_report',
    'vmec_jax_boozer_equal_arc_core_profiles_from_state',
    'vmec_jax_boozer_flux_tube_sensitivity_report',
    'vmec_jax_field_line_tensor_sensitivity_report',
    'vmec_jax_flux_tube_array_parity_report',
    'vmec_jax_flux_tube_mapping_from_state',
    'vmec_jax_flux_tube_sensitivity_report',
    'vmec_jax_metric_tensor_sensitivity_report',
    'vmec_boundary_aspect_sensitivity_report',
    'vmec_field_line_tensor_observable_names',
    'vmec_metric_tensor_observable_names',
    'J_l_all',
    'gamma0',
    'load_runtime_from_toml',
    'DiagnosticNorm',
    'NormalizationContract',
    'get_normalization_contract',
    'apply_diagnostic_normalization',
    'RuntimeConfig',
    'RuntimeSpeciesConfig',
    'RuntimePhysicsConfig',
    'RuntimeCollisionConfig',
    'RuntimeNormalizationConfig',
    'RuntimeOutputConfig',
    'RuntimeParallelConfig',
    'RuntimeQuasilinearConfig',
    'RuntimeTermsConfig',
    'QuasilinearTransportResult',
    'compute_quasilinear_from_linear_state',
    'effective_kperp2',
    'mixing_length_amplitude2_jax',
    'phi_norm2',
    'quasilinear_feature_objective',
    'saturation_amplitude2',
    'saturated_flux_from_linear_weight',
    'shape_aware_power_law_objective',
    'QuasilinearCalibrationPoint',
    'apply_heat_flux_scale',
    'calibration_point_from_nonlinear_window_summary',
    'calibration_point_from_spectrum_and_nonlinear_window',
    'fit_train_heat_flux_scale',
    'integrated_quasilinear_flux_from_spectrum',
    'quasilinear_calibration_report',
    'write_quasilinear_calibration_report',
    'build_quasilinear_model_selection_status',
    'build_quasilinear_model_selection_status_from_paths',
    'NonlinearWindowConvergenceConfig',
    'NonlinearWindowEnsembleConfig',
    'NonlinearWindowEnsembleManifestConfig',
    'nonlinear_window_convergence_from_csv',
    'nonlinear_window_convergence_from_summary',
    'nonlinear_window_convergence_report',
    'nonlinear_window_ensemble_artifact_manifest',
    'nonlinear_window_ensemble_report',
    'nonlinear_window_stats_promotion_ready',
    'ProductionNonlinearOptimizationGuardConfig',
    'matched_optimized_transport_report',
    'optimized_equilibrium_transport_report',
    'production_nonlinear_optimization_guard_report',
    'reduced_artifact_scope_report',
    'replicated_transport_ensemble_report',
    'RuntimeLinearResult',
    'RuntimeLinearScanResult',
    'build_runtime_linear_params',
    'build_runtime_linear_terms',
    'build_runtime_term_config',
    'run_linear_case',
    'run_nonlinear_case',
    'run_runtime_linear',
    'run_runtime_nonlinear',
    'run_runtime_scan',
    'hermite_streaming',
    'LinearParams',
    'LinearTerms',
    'LinearCache',
    'build_linear_cache',
    'linear_terms_to_term_config',
    'term_config_to_linear_terms',
    'linear_rhs',
    'linear_rhs_cached',
    'linear_rhs_electrostatic_slices_velocity_sharded',
    'linear_rhs_streaming_electrostatic_velocity_sharded',
    'linear_rhs_parallel_cached',
    'linear_rhs_streaming_velocity_sharded',
    'integrate_linear',
    'KrylovConfig',
    'dominant_eigenpair',
    'dominant_eigenvalue',
    'integrate_linear_diffrax',
    'integrate_linear_diffrax_streaming',
    'integrate_linear_sharded',
    'integrate_nonlinear_sharded',
    'integrate_nonlinear',
    'integrate_nonlinear_cached',
    'integrate_nonlinear_explicit_diagnostics',
    'integrate_nonlinear_diffrax',
    'build_nonlinear_imex_operator',
    'IMEXLinearOperator',
    'ExplicitTimeConfig',
    'integrate_linear_explicit',
    'integrate_linear_explicit_diagnostics',
    'SimulationDiagnostics',
    'nonlinear_rhs_cached',
    'integrate_linear_from_config',
    'integrate_nonlinear_from_config',
    'Species',
    'build_linear_params',
    'fit_growth_rate',
    'fit_growth_rate_auto',
    'instantaneous_growth_rate_from_phi',
    'growth_rate_from_phi',
    'select_fit_window',
    'ScanAndModeResult',
    'BranchContinuationMetrics',
    'ScalarGateResult',
    'GateReport',
    'LateTimeLinearMetrics',
    'NonlinearWindowMetrics',
    'ZonalFlowResponseMetrics',
    'branch_continuity_gate_report',
    'branch_continuity_metrics',
    'covariance_diagnostics',
    'autodiff_finite_difference_report',
    'central_finite_difference_jacobian',
    'explicit_complex_operator_matrix',
    'implicit_eigenpair_observable_sensitivity_report',
    'isolated_eigenpair_observable_sensitivity_report',
    'isolated_eigenvalue_sensitivity_report',
    'IndependentEnsembleProvenanceReport',
    'IndependentMapExecutionError',
    'IndependentWorkerMetadata',
    'ParallelIdentityReport',
    'batch_map',
    'batch_map_identity_report',
    'independent_ensemble_provenance_gate',
    'independent_map',
    'independent_map_identity_report',
    'independent_worker_metadata',
    'ky_scan_batches',
    'parallel_identity_report',
    'DecompositionContract',
    'ReconstructionIdentityReport',
    'ShardAssignment',
    'build_diagnostic_nonlinear_domain_decomposition',
    'build_independent_portfolio_decomposition',
    'reconstruct_serial',
    'serial_reconstruction_identity_report',
    'shard_sequence',
    'NonlinearDomainDecompositionPlan',
    'NonlinearDomainIdentityReport',
    'NonlinearDomainTransportWindowReport',
    'NonlinearParallelStrategy',
    'NonlinearSpectralCommunicationReport',
    'NonlinearSpectralDevicePencilFFTBatchModel',
    'NonlinearSpectralDevicePencilRHSIdentityReport',
    'NonlinearSpectralDevicePencilTransportWindowReport',
    'NonlinearSpectralDomainWorkModel',
    'NonlinearSpectralIntegratorIdentityReport',
    'NonlinearSpectralPencilRHSIdentityReport',
    'NonlinearSpectralPencilTransportWindowReport',
    'NonlinearSpectralPencilWorkModel',
    'NonlinearSpectralRHSIdentityReport',
    'build_nonlinear_domain_decomposition_plan',
    'classify_nonlinear_parallel_strategy',
    'deterministic_nonlinear_domain_state',
    'deterministic_nonlinear_spectral_state',
    'device_z_pencil_fft_batch_pressure_model',
    'device_z_pencil_nonlinear_spectral_rhs',
    'device_z_pencil_nonlinear_spectral_transport_window_identity_gate',
    'integrate_logical_decomposed_nonlinear_spectral',
    'nonlinear_domain_identity_report',
    'nonlinear_domain_parallel_identity_gate',
    'nonlinear_domain_transport_window_identity_gate',
    'nonlinear_parallel_strategies',
    'nonlinear_parallel_strategy',
    'nonlinear_spectral_communication_identity_gate',
    'nonlinear_spectral_communication_identity_report',
    'nonlinear_spectral_domain_work_model',
    'logical_decomposed_nonlinear_spectral_rhs',
    'nonlinear_spectral_integrator_identity_gate',
    'nonlinear_spectral_pencil_rhs_identity_gate',
    'nonlinear_spectral_pencil_transport_window_identity_gate',
    'nonlinear_spectral_pencil_work_model',
    'nonlinear_spectral_rhs_identity_gate',
    'nonlinear_spectral_rhs_identity_report',
    'pencil_decomposed_nonlinear_spectral_rhs',
    'local_stencil_nonlinear_domain_decomposed_step',
    'local_stencil_nonlinear_domain_serial_step',
    'release_ready_nonlinear_parallel_strategies',
    'VelocityShardingPlan',
    'build_velocity_sharding_plan',
    'curvature_gradb_drift_reference',
    'curvature_gradb_drift_shard_map',
    'diamagnetic_drive_reference',
    'diamagnetic_drive_shard_map',
    'electrostatic_phi_reference',
    'electrostatic_phi_shard_map',
    'hermite_neighbor_reference',
    'hermite_neighbor_shard_map',
    'hermite_shift_reference',
    'hermite_shift_shard_map',
    'hermite_streaming_ladder_reference',
    'hermite_streaming_ladder_shard_map',
    'mirror_drift_reference',
    'mirror_drift_shard_map',
    'periodic_streaming_reference',
    'periodic_streaming_shard_map',
    'velocity_field_reduce_reference',
    'velocity_field_reduce_shard_map',
    'QA_LOW_TURBULENCE_DESIGN_NAMES',
    'QA_LOW_TURBULENCE_OBSERVABLE_NAMES',
    'QALowTurbulenceConfig',
    'QALowTurbulenceResult',
    'default_qa_low_turbulence_initial_params',
    'optimize_qa_low_turbulence',
    'qa_low_turbulence_comparison_payload',
    'qa_low_turbulence_heat_flux_trace',
    'qa_low_turbulence_observable_sensitivity_report',
    'qa_low_turbulence_window_metrics',
    'qa_low_turbulence_observable_vector',
    'qa_low_turbulence_observables',
    'qa_low_turbulence_objective',
    'qa_low_turbulence_residual_names',
    'qa_low_turbulence_residual_vector',
    'reduced_boundary_surface',
    'reduced_lcfs_bmag',
    'STELLARATOR_ITG_OBSERVABLE_NAMES',
    'STELLARATOR_ITG_PARAMETER_NAMES',
    'StellaratorITGOptimizationConfig',
    'StellaratorITGOptimizationResult',
    'StellaratorITGSampleSet',
    'StellaratorObjectiveKind',
    'compare_stellarator_itg_objectives',
    'default_stellarator_initial_params',
    'nonlinear_heat_flux_trace',
    'nonlinear_heat_flux_window_metrics',
    'optimize_stellarator_itg',
    'qa_max_mode1_observables',
    'qa_observable_vector',
    'stellarator_itg_density_gradient_scan',
    'stellarator_itg_portfolio_gate_payload',
    'stellarator_itg_portfolio_sensitivity_report',
    'stellarator_itg_objective',
    'stellarator_itg_objective_residual_names',
    'stellarator_itg_objective_residual_vector',
    'stellarator_itg_reduced_portfolio_objective',
    'stellarator_itg_residual_sensitivity_report',
    'stellarator_itg_sample_objective_table',
    'stellarator_itg_vmec_boozer_portfolio_objective_from_state',
    'stellarator_itg_vmec_boozer_sample_objective_table_from_state',
    'StellaratorObjectivePortfolioContract',
    'ReducedPortfolioArtifactGuardConfig',
    'ProjectedLineSearchPolicy',
    'VMECJAXSpectraxTransportObjective',
    'VMECJAXTransportObjectiveConfig',
    'VMECJAXTransportObjectiveKind',
    'VMECJAXNonlinearAuditPolicy',
    'VMECJAXNonlinearCampaignPolicy',
    'VMECJAXReducedPrelaunchPolicy',
    'VMECJAXTransportAdmissionPolicy',
    'DEFAULT_TRANSPORT_METRIC_KEYS',
    'aggregate_objective_portfolio',
    'build_authoritative_wout_candidate_gate',
    'build_solved_vmec_candidate_gate',
    'build_wout_reproducibility_gate',
    'build_nonlinear_campaign_admission_report',
    'build_nonlinear_landscape_admission_report',
    'build_nonlinear_audit_redesign_report',
    'build_reduced_nonlinear_audit_prelaunch_report',
    'build_transport_admission_report',
    'boundary_spec_record',
    'boundary_chain_accepted_parameter_indices',
    'boundary_chain_summary_from_probe',
    'build_boundary_chain_collection_summary',
    'build_boundary_chain_summary',
    'candidate_transport_metric',
    'final_iota_profiles_from_vmec_result',
    'objective_portfolio_sensitivity_report',
    'portfolio_objective_weight_vector',
    'portfolio_sample_weight_tensor',
    'projected_line_search_input_manifest',
    'reduced_portfolio_artifact_guard_report',
    'validate_objective_portfolio_contract',
    'ZONAL_FLOW_OBJECTIVE_NAMES',
    'ZonalFlowObjectiveConfig',
    'zonal_flow_objective_artifact_from_records',
    'zonal_flow_objective_rows',
    'zonal_flow_objective_sensitivity_report',
    'zonal_flow_reduced_objective',
    'SOLVER_GEOMETRY_PARAMETER_NAMES',
    'SOLVER_OBJECTIVE_NAMES',
    'SolverScalarObjective',
    'VMEC_BOOZER_FREQUENCY_OBJECTIVE_NAMES',
    'VMEC_BOOZER_NONLINEAR_WINDOW_OBJECTIVE_NAMES',
    'VMEC_BOOZER_QUASILINEAR_OBJECTIVE_NAMES',
    'VMEC_BOOZER_STATE_PARAMETER_FAMILIES',
    'VMEC_BOOZER_STATE_PARAMETER_NAMES',
    'default_solver_geometry_design_params',
    'dominant_eigenvalue_branch_locality_report',
    'dominant_real_eigenvalue',
    'linear_solver_geometry_gradient_report',
    'mode21_vmec_boozer_linear_frequency_gradient_report',
    'mode21_vmec_boozer_nonlinear_window_gradient_report',
    'mode21_vmec_boozer_quasilinear_gradient_report',
    'solver_linear_operator_matrix_from_geometry',
    'solver_objective_branch_gradient_report',
    'solver_growth_rate_from_geometry',
    'solver_objective_vector_from_geometry',
    'solver_grid_options_from_ky_values',
    'solver_scalar_objective_from_vector',
    'spectrax_transport_objective_tuple',
    'select_admitted_transport_candidate',
    'transport_objective_sample_summary',
    'build_boundary_transport_gradient_report',
    'select_projected_line_search_candidate',
    'sparse_descent_direction_from_gradient_report',
    'vmec_jax_transport_growth_branch_locality_report_from_states',
    'vmec_jax_transport_objective_from_state',
    'write_boundary_transport_gradient_report',
    'solver_ready_geometry_mapping',
    'vmec_boozer_aggregate_line_search_holdout_report',
    'vmec_boozer_aggregate_scalar_objective_finite_difference_report',
    'vmec_boozer_aggregate_scalar_objective_from_state',
    'vmec_boozer_aggregate_scalar_objective_line_search_report',
    'vmec_boozer_scalar_objective_finite_difference_report',
    'vmec_boozer_scalar_objective_from_state',
    'vmec_boozer_scalar_objective_line_search_report',
    'vmec_boozer_solver_objective_table_from_state',
    'vmec_boozer_solver_objective_table_with_metadata_from_state',
    'vmec_boozer_solver_objective_vector_from_state',
    'eigenfunction_gate_report',
    'evaluate_scalar_gate',
    'gate_report',
    'gate_report_to_dict',
    'linear_metrics_gate_report',
    'nonlinear_window_gate_report',
    'observed_order_gate_report',
    'zonal_response_gate_report',
    'normalize_eigenfunction',
    'run_linear_scan',
    'run_scan_and_mode',
    'ModeSelection',
    'extract_mode',
    'extract_mode_time_series',
    'extract_eigenfunction',
    'select_ky_index',
    'cyclone_reference_figure',
    'cyclone_comparison_figure',
    'etg_trend_figure',
    'growth_rate_heatmap',
    'growth_fit_figure',
    'linear_validation_figure',
    'LinearValidationPanel',
    'MultiReferenceValidationPanel',
    'ReferenceSeries',
    'linear_validation_multi_reference_figure',
    'scan_multi_reference_figure',
    'scan_comparison_figure',
    'set_plot_style',
]

_EXPORT_TARGETS: dict[str, tuple[str, str]] = {
    'CycloneBaseCase': ('spectraxgk.config', 'CycloneBaseCase'),
    'GridConfig': ('spectraxgk.config', 'GridConfig'),
    'KineticElectronBaseCase': ('spectraxgk.config', 'KineticElectronBaseCase'),
    'KBMBaseCase': ('spectraxgk.config', 'KBMBaseCase'),
    'TEMBaseCase': ('spectraxgk.config', 'TEMBaseCase'),
    'TimeConfig': ('spectraxgk.config', 'TimeConfig'),
    'SAlphaGeometry': ('spectraxgk.geometry', 'SAlphaGeometry'),
    'build_flux_tube_geometry': ('spectraxgk.geometry', 'build_flux_tube_geometry'),
    'booz_xform_flux_tube_mapping_from_inputs': ('spectraxgk.geometry.differentiable', 'booz_xform_flux_tube_mapping_from_inputs'),
    'booz_xform_flux_tube_sensitivity_report': ('spectraxgk.geometry.differentiable', 'booz_xform_flux_tube_sensitivity_report'),
    'booz_xform_spectral_sensitivity_report': ('spectraxgk.geometry.differentiable', 'booz_xform_spectral_sensitivity_report'),
    'discover_differentiable_geometry_backends': ('spectraxgk.geometry.differentiable', 'discover_differentiable_geometry_backends'),
    'evaluate_boozer_bmag_on_field_line': ('spectraxgk.geometry.differentiable', 'evaluate_boozer_bmag_on_field_line'),
    'finite_difference_jacobian': ('spectraxgk.geometry.differentiable', 'finite_difference_jacobian'),
    'flux_tube_geometry_from_mapping': ('spectraxgk.geometry.differentiable', 'flux_tube_geometry_from_mapping'),
    'flux_tube_geometry_from_vmec_boozer_state': ('spectraxgk.geometry.differentiable', 'flux_tube_geometry_from_vmec_boozer_state'),
    'flux_tube_geometry_observables': ('spectraxgk.geometry.differentiable', 'flux_tube_geometry_observables'),
    'geometry_inverse_design_report': ('spectraxgk.geometry.differentiable', 'geometry_inverse_design_report'),
    'geometry_observable_names': ('spectraxgk.geometry.differentiable', 'geometry_observable_names'),
    'geometry_sensitivity_report': ('spectraxgk.geometry.differentiable', 'geometry_sensitivity_report'),
    'vmec_jax_boozer_equal_arc_core_profiles_from_state': ('spectraxgk.geometry.differentiable', 'vmec_jax_boozer_equal_arc_core_profiles_from_state'),
    'vmec_jax_boozer_flux_tube_sensitivity_report': ('spectraxgk.geometry.differentiable', 'vmec_jax_boozer_flux_tube_sensitivity_report'),
    'vmec_jax_field_line_tensor_sensitivity_report': ('spectraxgk.geometry.differentiable', 'vmec_jax_field_line_tensor_sensitivity_report'),
    'vmec_jax_flux_tube_array_parity_report': ('spectraxgk.geometry.differentiable', 'vmec_jax_flux_tube_array_parity_report'),
    'vmec_jax_flux_tube_mapping_from_state': ('spectraxgk.geometry.differentiable', 'vmec_jax_flux_tube_mapping_from_state'),
    'vmec_jax_flux_tube_sensitivity_report': ('spectraxgk.geometry.differentiable', 'vmec_jax_flux_tube_sensitivity_report'),
    'vmec_jax_metric_tensor_sensitivity_report': ('spectraxgk.geometry.differentiable', 'vmec_jax_metric_tensor_sensitivity_report'),
    'vmec_boundary_aspect_sensitivity_report': ('spectraxgk.geometry.differentiable', 'vmec_boundary_aspect_sensitivity_report'),
    'vmec_field_line_tensor_observable_names': ('spectraxgk.geometry.differentiable', 'vmec_field_line_tensor_observable_names'),
    'vmec_metric_tensor_observable_names': ('spectraxgk.geometry.differentiable', 'vmec_metric_tensor_observable_names'),
    'J_l_all': ('spectraxgk.core.velocity', 'J_l_all'),
    'gamma0': ('spectraxgk.core.velocity', 'gamma0'),
    'load_runtime_from_toml': ('spectraxgk.workflows.runtime.toml', 'load_runtime_from_toml'),
    'DiagnosticNorm': ('spectraxgk.diagnostics.normalization', 'DiagnosticNorm'),
    'NormalizationContract': ('spectraxgk.diagnostics.normalization', 'NormalizationContract'),
    'get_normalization_contract': ('spectraxgk.diagnostics.normalization', 'get_normalization_contract'),
    'apply_diagnostic_normalization': ('spectraxgk.diagnostics.normalization', 'apply_diagnostic_normalization'),
    'RuntimeConfig': ('spectraxgk.workflows.runtime.config', 'RuntimeConfig'),
    'RuntimeSpeciesConfig': ('spectraxgk.workflows.runtime.config', 'RuntimeSpeciesConfig'),
    'RuntimePhysicsConfig': ('spectraxgk.workflows.runtime.config', 'RuntimePhysicsConfig'),
    'RuntimeCollisionConfig': ('spectraxgk.workflows.runtime.config', 'RuntimeCollisionConfig'),
    'RuntimeNormalizationConfig': ('spectraxgk.workflows.runtime.config', 'RuntimeNormalizationConfig'),
    'RuntimeOutputConfig': ('spectraxgk.workflows.runtime.config', 'RuntimeOutputConfig'),
    'RuntimeParallelConfig': ('spectraxgk.workflows.runtime.config', 'RuntimeParallelConfig'),
    'RuntimeQuasilinearConfig': ('spectraxgk.workflows.runtime.config', 'RuntimeQuasilinearConfig'),
    'RuntimeTermsConfig': ('spectraxgk.workflows.runtime.config', 'RuntimeTermsConfig'),
    'QuasilinearTransportResult': ('spectraxgk.diagnostics.quasilinear_transport', 'QuasilinearTransportResult'),
    'compute_quasilinear_from_linear_state': ('spectraxgk.diagnostics.quasilinear_transport', 'compute_quasilinear_from_linear_state'),
    'effective_kperp2': ('spectraxgk.diagnostics.quasilinear_transport', 'effective_kperp2'),
    'mixing_length_amplitude2_jax': ('spectraxgk.diagnostics.quasilinear_transport', 'mixing_length_amplitude2_jax'),
    'phi_norm2': ('spectraxgk.diagnostics.quasilinear_transport', 'phi_norm2'),
    'quasilinear_feature_objective': ('spectraxgk.diagnostics.quasilinear_transport', 'quasilinear_feature_objective'),
    'saturation_amplitude2': ('spectraxgk.diagnostics.quasilinear_transport', 'saturation_amplitude2'),
    'saturated_flux_from_linear_weight': ('spectraxgk.diagnostics.quasilinear_transport', 'saturated_flux_from_linear_weight'),
    'shape_aware_power_law_objective': ('spectraxgk.diagnostics.quasilinear_transport', 'shape_aware_power_law_objective'),
    'QuasilinearCalibrationPoint': ('spectraxgk.diagnostics.quasilinear_calibration', 'QuasilinearCalibrationPoint'),
    'apply_heat_flux_scale': ('spectraxgk.diagnostics.quasilinear_calibration', 'apply_heat_flux_scale'),
    'calibration_point_from_nonlinear_window_summary': ('spectraxgk.diagnostics.quasilinear_calibration', 'calibration_point_from_nonlinear_window_summary'),
    'calibration_point_from_spectrum_and_nonlinear_window': ('spectraxgk.diagnostics.quasilinear_calibration', 'calibration_point_from_spectrum_and_nonlinear_window'),
    'fit_train_heat_flux_scale': ('spectraxgk.diagnostics.quasilinear_calibration', 'fit_train_heat_flux_scale'),
    'integrated_quasilinear_flux_from_spectrum': ('spectraxgk.diagnostics.quasilinear_calibration', 'integrated_quasilinear_flux_from_spectrum'),
    'quasilinear_calibration_report': ('spectraxgk.diagnostics.quasilinear_calibration', 'quasilinear_calibration_report'),
    'write_quasilinear_calibration_report': ('spectraxgk.diagnostics.quasilinear_calibration', 'write_quasilinear_calibration_report'),
    'build_quasilinear_model_selection_status': ('spectraxgk.diagnostics.quasilinear_model_selection', 'build_quasilinear_model_selection_status'),
    'build_quasilinear_model_selection_status_from_paths': ('spectraxgk.diagnostics.quasilinear_model_selection', 'build_quasilinear_model_selection_status_from_paths'),
    'NonlinearWindowConvergenceConfig': ('spectraxgk.diagnostics.transport_windows', 'NonlinearWindowConvergenceConfig'),
    'NonlinearWindowEnsembleConfig': ('spectraxgk.diagnostics.transport_windows', 'NonlinearWindowEnsembleConfig'),
    'NonlinearWindowEnsembleManifestConfig': ('spectraxgk.diagnostics.transport_windows', 'NonlinearWindowEnsembleManifestConfig'),
    'nonlinear_window_convergence_from_csv': ('spectraxgk.diagnostics.transport_windows', 'nonlinear_window_convergence_from_csv'),
    'nonlinear_window_convergence_from_summary': ('spectraxgk.diagnostics.transport_windows', 'nonlinear_window_convergence_from_summary'),
    'nonlinear_window_convergence_report': ('spectraxgk.diagnostics.transport_windows', 'nonlinear_window_convergence_report'),
    'nonlinear_window_ensemble_artifact_manifest': ('spectraxgk.diagnostics.transport_windows', 'nonlinear_window_ensemble_artifact_manifest'),
    'nonlinear_window_ensemble_report': ('spectraxgk.diagnostics.transport_windows', 'nonlinear_window_ensemble_report'),
    'nonlinear_window_stats_promotion_ready': ('spectraxgk.diagnostics.transport_windows', 'nonlinear_window_stats_promotion_ready'),
    'ProductionNonlinearOptimizationGuardConfig': ('spectraxgk.diagnostics.nonlinear_transport_optimization', 'ProductionNonlinearOptimizationGuardConfig'),
    'matched_optimized_transport_report': ('spectraxgk.diagnostics.nonlinear_transport_optimization', 'matched_optimized_transport_report'),
    'optimized_equilibrium_transport_report': ('spectraxgk.diagnostics.nonlinear_transport_optimization', 'optimized_equilibrium_transport_report'),
    'production_nonlinear_optimization_guard_report': ('spectraxgk.diagnostics.nonlinear_transport_optimization', 'production_nonlinear_optimization_guard_report'),
    'reduced_artifact_scope_report': ('spectraxgk.diagnostics.nonlinear_transport_optimization', 'reduced_artifact_scope_report'),
    'replicated_transport_ensemble_report': ('spectraxgk.diagnostics.nonlinear_transport_optimization', 'replicated_transport_ensemble_report'),
    'RuntimeLinearResult': ('spectraxgk.runtime', 'RuntimeLinearResult'),
    'RuntimeLinearScanResult': ('spectraxgk.runtime', 'RuntimeLinearScanResult'),
    'build_runtime_linear_params': ('spectraxgk.runtime', 'build_runtime_linear_params'),
    'build_runtime_linear_terms': ('spectraxgk.runtime', 'build_runtime_linear_terms'),
    'build_runtime_term_config': ('spectraxgk.runtime', 'build_runtime_term_config'),
    'run_linear_case': ('spectraxgk.runtime', 'run_linear_case'),
    'run_nonlinear_case': ('spectraxgk.runtime', 'run_nonlinear_case'),
    'run_runtime_linear': ('spectraxgk.runtime', 'run_runtime_linear'),
    'run_runtime_nonlinear': ('spectraxgk.runtime', 'run_runtime_nonlinear'),
    'run_runtime_scan': ('spectraxgk.runtime', 'run_runtime_scan'),
    'hermite_streaming': ('spectraxgk.operators', 'hermite_streaming'),
    'LinearParams': ('spectraxgk.linear', 'LinearParams'),
    'LinearTerms': ('spectraxgk.linear', 'LinearTerms'),
    'LinearCache': ('spectraxgk.linear', 'LinearCache'),
    'build_linear_cache': ('spectraxgk.linear', 'build_linear_cache'),
    'linear_terms_to_term_config': ('spectraxgk.linear', 'linear_terms_to_term_config'),
    'term_config_to_linear_terms': ('spectraxgk.linear', 'term_config_to_linear_terms'),
    'linear_rhs': ('spectraxgk.linear', 'linear_rhs'),
    'linear_rhs_cached': ('spectraxgk.linear', 'linear_rhs_cached'),
    'linear_rhs_electrostatic_slices_velocity_sharded': ('spectraxgk.linear', 'linear_rhs_electrostatic_slices_velocity_sharded'),
    'linear_rhs_streaming_electrostatic_velocity_sharded': ('spectraxgk.linear', 'linear_rhs_streaming_electrostatic_velocity_sharded'),
    'linear_rhs_parallel_cached': ('spectraxgk.linear', 'linear_rhs_parallel_cached'),
    'linear_rhs_streaming_velocity_sharded': ('spectraxgk.linear', 'linear_rhs_streaming_velocity_sharded'),
    'integrate_linear': ('spectraxgk.linear', 'integrate_linear'),
    'KrylovConfig': ('spectraxgk.solvers.linear.krylov', 'KrylovConfig'),
    'dominant_eigenpair': ('spectraxgk.solvers.linear.krylov', 'dominant_eigenpair'),
    'dominant_eigenvalue': ('spectraxgk.solvers.linear.krylov', 'dominant_eigenvalue'),
    'integrate_linear_diffrax': ('spectraxgk.solvers.time.diffrax_linear', 'integrate_linear_diffrax'),
    'integrate_linear_diffrax_streaming': ('spectraxgk.solvers.time.diffrax_streaming', 'integrate_linear_diffrax_streaming'),
    'integrate_linear_sharded': ('spectraxgk.parallel.integrators', 'integrate_linear_sharded'),
    'integrate_nonlinear_sharded': ('spectraxgk.parallel.integrators', 'integrate_nonlinear_sharded'),
    'integrate_nonlinear': ('spectraxgk.nonlinear', 'integrate_nonlinear'),
    'integrate_nonlinear_cached': ('spectraxgk.nonlinear', 'integrate_nonlinear_cached'),
    'integrate_nonlinear_explicit_diagnostics': ('spectraxgk.nonlinear', 'integrate_nonlinear_explicit_diagnostics'),
    'integrate_nonlinear_diffrax': ('spectraxgk.solvers.time.diffrax_nonlinear', 'integrate_nonlinear_diffrax'),
    'build_nonlinear_imex_operator': ('spectraxgk.nonlinear', 'build_nonlinear_imex_operator'),
    'IMEXLinearOperator': ('spectraxgk.nonlinear', 'IMEXLinearOperator'),
    'ExplicitTimeConfig': ('spectraxgk.solvers.time.explicit', 'ExplicitTimeConfig'),
    'integrate_linear_explicit': ('spectraxgk.solvers.time.explicit', 'integrate_linear_explicit'),
    'integrate_linear_explicit_diagnostics': ('spectraxgk.solvers.time.explicit', 'integrate_linear_explicit_diagnostics'),
    'SimulationDiagnostics': ('spectraxgk.diagnostics', 'SimulationDiagnostics'),
    'nonlinear_rhs_cached': ('spectraxgk.nonlinear', 'nonlinear_rhs_cached'),
    'integrate_linear_from_config': ('spectraxgk.solvers.time.runners', 'integrate_linear_from_config'),
    'integrate_nonlinear_from_config': ('spectraxgk.solvers.time.runners', 'integrate_nonlinear_from_config'),
    'Species': ('spectraxgk.core.species', 'Species'),
    'build_linear_params': ('spectraxgk.core.species', 'build_linear_params'),
    'fit_growth_rate': ('spectraxgk.diagnostics.analysis', 'fit_growth_rate'),
    'fit_growth_rate_auto': ('spectraxgk.diagnostics.analysis', 'fit_growth_rate_auto'),
    'instantaneous_growth_rate_from_phi': ('spectraxgk.diagnostics.analysis', 'instantaneous_growth_rate_from_phi'),
    'growth_rate_from_phi': ('spectraxgk.diagnostics.analysis', 'instantaneous_growth_rate_from_phi'),
    'select_fit_window': ('spectraxgk.diagnostics.analysis', 'select_fit_window'),
    'ScanAndModeResult': ('spectraxgk.workflows.linear', 'ScanAndModeResult'),
    'BranchContinuationMetrics': ('spectraxgk.diagnostics.validation_gates', 'BranchContinuationMetrics'),
    'ScalarGateResult': ('spectraxgk.diagnostics.validation_gates', 'ScalarGateResult'),
    'GateReport': ('spectraxgk.diagnostics.validation_gates', 'GateReport'),
    'LateTimeLinearMetrics': ('spectraxgk.diagnostics.validation_gates', 'LateTimeLinearMetrics'),
    'NonlinearWindowMetrics': ('spectraxgk.diagnostics.validation_gates', 'NonlinearWindowMetrics'),
    'ZonalFlowResponseMetrics': ('spectraxgk.diagnostics.validation_gates', 'ZonalFlowResponseMetrics'),
    'branch_continuity_gate_report': ('spectraxgk.diagnostics.validation_gates', 'branch_continuity_gate_report'),
    'branch_continuity_metrics': ('spectraxgk.diagnostics.validation_gates', 'branch_continuity_metrics'),
    'covariance_diagnostics': ('spectraxgk.objectives.autodiff_validation', 'covariance_diagnostics'),
    'autodiff_finite_difference_report': ('spectraxgk.objectives.autodiff_validation', 'autodiff_finite_difference_report'),
    'central_finite_difference_jacobian': ('spectraxgk.objectives.autodiff_validation', 'central_finite_difference_jacobian'),
    'explicit_complex_operator_matrix': ('spectraxgk.objectives.autodiff_validation', 'explicit_complex_operator_matrix'),
    'implicit_eigenpair_observable_sensitivity_report': ('spectraxgk.objectives.autodiff_validation', 'implicit_eigenpair_observable_sensitivity_report'),
    'isolated_eigenpair_observable_sensitivity_report': ('spectraxgk.objectives.autodiff_validation', 'isolated_eigenpair_observable_sensitivity_report'),
    'isolated_eigenvalue_sensitivity_report': ('spectraxgk.objectives.autodiff_validation', 'isolated_eigenvalue_sensitivity_report'),
    'IndependentEnsembleProvenanceReport': ('spectraxgk.parallel', 'IndependentEnsembleProvenanceReport'),
    'IndependentMapExecutionError': ('spectraxgk.parallel', 'IndependentMapExecutionError'),
    'IndependentWorkerMetadata': ('spectraxgk.parallel', 'IndependentWorkerMetadata'),
    'ParallelIdentityReport': ('spectraxgk.parallel', 'ParallelIdentityReport'),
    'batch_map': ('spectraxgk.parallel', 'batch_map'),
    'batch_map_identity_report': ('spectraxgk.parallel', 'batch_map_identity_report'),
    'independent_ensemble_provenance_gate': ('spectraxgk.parallel', 'independent_ensemble_provenance_gate'),
    'independent_map': ('spectraxgk.parallel', 'independent_map'),
    'independent_map_identity_report': ('spectraxgk.parallel', 'independent_map_identity_report'),
    'independent_worker_metadata': ('spectraxgk.parallel', 'independent_worker_metadata'),
    'ky_scan_batches': ('spectraxgk.parallel', 'ky_scan_batches'),
    'parallel_identity_report': ('spectraxgk.parallel', 'parallel_identity_report'),
    'DecompositionContract': ('spectraxgk.parallel.decomposition', 'DecompositionContract'),
    'ReconstructionIdentityReport': ('spectraxgk.parallel.decomposition', 'ReconstructionIdentityReport'),
    'ShardAssignment': ('spectraxgk.parallel.decomposition', 'ShardAssignment'),
    'build_diagnostic_nonlinear_domain_decomposition': ('spectraxgk.parallel.decomposition', 'build_diagnostic_nonlinear_domain_decomposition'),
    'build_independent_portfolio_decomposition': ('spectraxgk.parallel.decomposition', 'build_independent_portfolio_decomposition'),
    'reconstruct_serial': ('spectraxgk.parallel.decomposition', 'reconstruct_serial'),
    'serial_reconstruction_identity_report': ('spectraxgk.parallel.decomposition', 'serial_reconstruction_identity_report'),
    'shard_sequence': ('spectraxgk.parallel.decomposition', 'shard_sequence'),
    'NonlinearDomainDecompositionPlan': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearDomainDecompositionPlan'),
    'NonlinearDomainIdentityReport': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearDomainIdentityReport'),
    'NonlinearDomainTransportWindowReport': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearDomainTransportWindowReport'),
    'NonlinearParallelStrategy': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearParallelStrategy'),
    'NonlinearSpectralCommunicationReport': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralCommunicationReport'),
    'NonlinearSpectralDevicePencilFFTBatchModel': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralDevicePencilFFTBatchModel'),
    'NonlinearSpectralDevicePencilRHSIdentityReport': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralDevicePencilRHSIdentityReport'),
    'NonlinearSpectralDevicePencilTransportWindowReport': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralDevicePencilTransportWindowReport'),
    'NonlinearSpectralDomainWorkModel': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralDomainWorkModel'),
    'NonlinearSpectralIntegratorIdentityReport': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralIntegratorIdentityReport'),
    'NonlinearSpectralPencilRHSIdentityReport': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralPencilRHSIdentityReport'),
    'NonlinearSpectralPencilTransportWindowReport': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralPencilTransportWindowReport'),
    'NonlinearSpectralPencilWorkModel': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralPencilWorkModel'),
    'NonlinearSpectralRHSIdentityReport': ('spectraxgk.operators.nonlinear.parallel', 'NonlinearSpectralRHSIdentityReport'),
    'build_nonlinear_domain_decomposition_plan': ('spectraxgk.operators.nonlinear.parallel', 'build_nonlinear_domain_decomposition_plan'),
    'classify_nonlinear_parallel_strategy': ('spectraxgk.operators.nonlinear.parallel', 'classify_nonlinear_parallel_strategy'),
    'deterministic_nonlinear_domain_state': ('spectraxgk.operators.nonlinear.parallel', 'deterministic_nonlinear_domain_state'),
    'deterministic_nonlinear_spectral_state': ('spectraxgk.operators.nonlinear.parallel', 'deterministic_nonlinear_spectral_state'),
    'device_z_pencil_fft_batch_pressure_model': ('spectraxgk.operators.nonlinear.parallel', 'device_z_pencil_fft_batch_pressure_model'),
    'device_z_pencil_nonlinear_spectral_rhs': ('spectraxgk.operators.nonlinear.parallel', 'device_z_pencil_nonlinear_spectral_rhs'),
    'device_z_pencil_nonlinear_spectral_transport_window_identity_gate': ('spectraxgk.operators.nonlinear.parallel', 'device_z_pencil_nonlinear_spectral_transport_window_identity_gate'),
    'integrate_logical_decomposed_nonlinear_spectral': ('spectraxgk.operators.nonlinear.parallel', 'integrate_logical_decomposed_nonlinear_spectral'),
    'nonlinear_domain_identity_report': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_domain_identity_report'),
    'nonlinear_domain_parallel_identity_gate': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_domain_parallel_identity_gate'),
    'nonlinear_domain_transport_window_identity_gate': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_domain_transport_window_identity_gate'),
    'nonlinear_parallel_strategies': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_parallel_strategies'),
    'nonlinear_parallel_strategy': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_parallel_strategy'),
    'nonlinear_spectral_communication_identity_gate': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_spectral_communication_identity_gate'),
    'nonlinear_spectral_communication_identity_report': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_spectral_communication_identity_report'),
    'nonlinear_spectral_domain_work_model': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_spectral_domain_work_model'),
    'logical_decomposed_nonlinear_spectral_rhs': ('spectraxgk.operators.nonlinear.parallel', 'logical_decomposed_nonlinear_spectral_rhs'),
    'nonlinear_spectral_integrator_identity_gate': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_spectral_integrator_identity_gate'),
    'nonlinear_spectral_pencil_rhs_identity_gate': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_spectral_pencil_rhs_identity_gate'),
    'nonlinear_spectral_pencil_transport_window_identity_gate': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_spectral_pencil_transport_window_identity_gate'),
    'nonlinear_spectral_pencil_work_model': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_spectral_pencil_work_model'),
    'nonlinear_spectral_rhs_identity_gate': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_spectral_rhs_identity_gate'),
    'nonlinear_spectral_rhs_identity_report': ('spectraxgk.operators.nonlinear.parallel', 'nonlinear_spectral_rhs_identity_report'),
    'pencil_decomposed_nonlinear_spectral_rhs': ('spectraxgk.operators.nonlinear.parallel', 'pencil_decomposed_nonlinear_spectral_rhs'),
    'local_stencil_nonlinear_domain_decomposed_step': ('spectraxgk.operators.nonlinear.parallel', 'local_stencil_nonlinear_domain_decomposed_step'),
    'local_stencil_nonlinear_domain_serial_step': ('spectraxgk.operators.nonlinear.parallel', 'local_stencil_nonlinear_domain_serial_step'),
    'release_ready_nonlinear_parallel_strategies': ('spectraxgk.operators.nonlinear.parallel', 'release_ready_nonlinear_parallel_strategies'),
    'VelocityShardingPlan': ('spectraxgk.parallel.velocity', 'VelocityShardingPlan'),
    'build_velocity_sharding_plan': ('spectraxgk.parallel.velocity', 'build_velocity_sharding_plan'),
    'curvature_gradb_drift_reference': ('spectraxgk.parallel.velocity', 'curvature_gradb_drift_reference'),
    'curvature_gradb_drift_shard_map': ('spectraxgk.parallel.velocity', 'curvature_gradb_drift_shard_map'),
    'diamagnetic_drive_reference': ('spectraxgk.parallel.velocity', 'diamagnetic_drive_reference'),
    'diamagnetic_drive_shard_map': ('spectraxgk.parallel.velocity', 'diamagnetic_drive_shard_map'),
    'electrostatic_phi_reference': ('spectraxgk.parallel.velocity', 'electrostatic_phi_reference'),
    'electrostatic_phi_shard_map': ('spectraxgk.parallel.velocity', 'electrostatic_phi_shard_map'),
    'hermite_neighbor_reference': ('spectraxgk.parallel.velocity', 'hermite_neighbor_reference'),
    'hermite_neighbor_shard_map': ('spectraxgk.parallel.velocity', 'hermite_neighbor_shard_map'),
    'hermite_shift_reference': ('spectraxgk.parallel.velocity', 'hermite_shift_reference'),
    'hermite_shift_shard_map': ('spectraxgk.parallel.velocity', 'hermite_shift_shard_map'),
    'hermite_streaming_ladder_reference': ('spectraxgk.parallel.velocity', 'hermite_streaming_ladder_reference'),
    'hermite_streaming_ladder_shard_map': ('spectraxgk.parallel.velocity', 'hermite_streaming_ladder_shard_map'),
    'mirror_drift_reference': ('spectraxgk.parallel.velocity', 'mirror_drift_reference'),
    'mirror_drift_shard_map': ('spectraxgk.parallel.velocity', 'mirror_drift_shard_map'),
    'periodic_streaming_reference': ('spectraxgk.parallel.velocity', 'periodic_streaming_reference'),
    'periodic_streaming_shard_map': ('spectraxgk.parallel.velocity', 'periodic_streaming_shard_map'),
    'velocity_field_reduce_reference': ('spectraxgk.parallel.velocity', 'velocity_field_reduce_reference'),
    'velocity_field_reduce_shard_map': ('spectraxgk.parallel.velocity', 'velocity_field_reduce_shard_map'),
    'QA_LOW_TURBULENCE_DESIGN_NAMES': ('spectraxgk.objectives.qa_low_turbulence', 'QA_LOW_TURBULENCE_DESIGN_NAMES'),
    'QA_LOW_TURBULENCE_OBSERVABLE_NAMES': ('spectraxgk.objectives.qa_low_turbulence', 'QA_LOW_TURBULENCE_OBSERVABLE_NAMES'),
    'QALowTurbulenceConfig': ('spectraxgk.objectives.qa_low_turbulence', 'QALowTurbulenceConfig'),
    'QALowTurbulenceResult': ('spectraxgk.objectives.qa_low_turbulence', 'QALowTurbulenceResult'),
    'default_qa_low_turbulence_initial_params': ('spectraxgk.objectives.qa_low_turbulence', 'default_qa_low_turbulence_initial_params'),
    'optimize_qa_low_turbulence': ('spectraxgk.objectives.qa_low_turbulence', 'optimize_qa_low_turbulence'),
    'qa_low_turbulence_comparison_payload': ('spectraxgk.objectives.qa_low_turbulence', 'qa_low_turbulence_comparison_payload'),
    'qa_low_turbulence_heat_flux_trace': ('spectraxgk.objectives.qa_low_turbulence', 'qa_low_turbulence_heat_flux_trace'),
    'qa_low_turbulence_observable_sensitivity_report': ('spectraxgk.objectives.qa_low_turbulence', 'qa_low_turbulence_observable_sensitivity_report'),
    'qa_low_turbulence_window_metrics': ('spectraxgk.objectives.qa_low_turbulence', 'qa_low_turbulence_window_metrics'),
    'qa_low_turbulence_observable_vector': ('spectraxgk.objectives.qa_low_turbulence', 'qa_low_turbulence_observable_vector'),
    'qa_low_turbulence_observables': ('spectraxgk.objectives.qa_low_turbulence', 'qa_low_turbulence_observables'),
    'qa_low_turbulence_objective': ('spectraxgk.objectives.qa_low_turbulence', 'qa_low_turbulence_objective'),
    'qa_low_turbulence_residual_names': ('spectraxgk.objectives.qa_low_turbulence', 'qa_low_turbulence_residual_names'),
    'qa_low_turbulence_residual_vector': ('spectraxgk.objectives.qa_low_turbulence', 'qa_low_turbulence_residual_vector'),
    'reduced_boundary_surface': ('spectraxgk.objectives.qa_low_turbulence', 'reduced_boundary_surface'),
    'reduced_lcfs_bmag': ('spectraxgk.objectives.qa_low_turbulence', 'reduced_lcfs_bmag'),
    'STELLARATOR_ITG_OBSERVABLE_NAMES': ('spectraxgk.objectives.stellarator', 'OBSERVABLE_NAMES'),
    'STELLARATOR_ITG_PARAMETER_NAMES': ('spectraxgk.objectives.stellarator', 'PARAMETER_NAMES'),
    'StellaratorITGOptimizationConfig': ('spectraxgk.objectives.stellarator', 'StellaratorITGOptimizationConfig'),
    'StellaratorITGOptimizationResult': ('spectraxgk.objectives.stellarator', 'StellaratorITGOptimizationResult'),
    'StellaratorITGSampleSet': ('spectraxgk.objectives.stellarator', 'StellaratorITGSampleSet'),
    'StellaratorObjectiveKind': ('spectraxgk.objectives.stellarator', 'StellaratorObjectiveKind'),
    'compare_stellarator_itg_objectives': ('spectraxgk.objectives.stellarator', 'compare_stellarator_itg_objectives'),
    'default_stellarator_initial_params': ('spectraxgk.objectives.stellarator', 'default_stellarator_initial_params'),
    'nonlinear_heat_flux_trace': ('spectraxgk.objectives.stellarator', 'nonlinear_heat_flux_trace'),
    'nonlinear_heat_flux_window_metrics': ('spectraxgk.objectives.stellarator', 'nonlinear_heat_flux_window_metrics'),
    'optimize_stellarator_itg': ('spectraxgk.objectives.stellarator', 'optimize_stellarator_itg'),
    'qa_max_mode1_observables': ('spectraxgk.objectives.stellarator', 'qa_max_mode1_observables'),
    'qa_observable_vector': ('spectraxgk.objectives.stellarator', 'qa_observable_vector'),
    'stellarator_itg_density_gradient_scan': ('spectraxgk.objectives.stellarator', 'stellarator_itg_density_gradient_scan'),
    'stellarator_itg_portfolio_gate_payload': ('spectraxgk.objectives.stellarator', 'stellarator_itg_portfolio_gate_payload'),
    'stellarator_itg_portfolio_sensitivity_report': ('spectraxgk.objectives.stellarator', 'stellarator_itg_portfolio_sensitivity_report'),
    'stellarator_itg_objective': ('spectraxgk.objectives.stellarator', 'stellarator_itg_objective'),
    'stellarator_itg_objective_residual_names': ('spectraxgk.objectives.stellarator', 'stellarator_itg_objective_residual_names'),
    'stellarator_itg_objective_residual_vector': ('spectraxgk.objectives.stellarator', 'stellarator_itg_objective_residual_vector'),
    'stellarator_itg_reduced_portfolio_objective': ('spectraxgk.objectives.stellarator', 'stellarator_itg_reduced_portfolio_objective'),
    'stellarator_itg_residual_sensitivity_report': ('spectraxgk.objectives.stellarator', 'stellarator_itg_residual_sensitivity_report'),
    'stellarator_itg_sample_objective_table': ('spectraxgk.objectives.stellarator', 'stellarator_itg_sample_objective_table'),
    'stellarator_itg_vmec_boozer_portfolio_objective_from_state': ('spectraxgk.objectives.stellarator', 'stellarator_itg_vmec_boozer_portfolio_objective_from_state'),
    'stellarator_itg_vmec_boozer_sample_objective_table_from_state': ('spectraxgk.objectives.stellarator', 'stellarator_itg_vmec_boozer_sample_objective_table_from_state'),
    'StellaratorObjectivePortfolioContract': ('spectraxgk.objectives.portfolio_contracts', 'StellaratorObjectivePortfolioContract'),
    'ReducedPortfolioArtifactGuardConfig': ('spectraxgk.objectives.portfolio_artifacts', 'ReducedPortfolioArtifactGuardConfig'),
    'ProjectedLineSearchPolicy': ('spectraxgk.objectives.vmec_transport_line_search', 'ProjectedLineSearchPolicy'),
    'VMECJAXSpectraxTransportObjective': ('spectraxgk.objectives.vmec_transport', 'VMECJAXSpectraxTransportObjective'),
    'VMECJAXTransportObjectiveConfig': ('spectraxgk.objectives.vmec_transport', 'VMECJAXTransportObjectiveConfig'),
    'VMECJAXTransportObjectiveKind': ('spectraxgk.objectives.vmec_transport', 'VMECJAXTransportObjectiveKind'),
    'VMECJAXNonlinearAuditPolicy': ('spectraxgk.objectives.vmec_transport_admission', 'VMECJAXNonlinearAuditPolicy'),
    'VMECJAXNonlinearCampaignPolicy': ('spectraxgk.objectives.vmec_transport_admission', 'VMECJAXNonlinearCampaignPolicy'),
    'VMECJAXReducedPrelaunchPolicy': ('spectraxgk.objectives.vmec_transport_admission', 'VMECJAXReducedPrelaunchPolicy'),
    'VMECJAXTransportAdmissionPolicy': ('spectraxgk.objectives.vmec_transport_admission', 'VMECJAXTransportAdmissionPolicy'),
    'DEFAULT_TRANSPORT_METRIC_KEYS': ('spectraxgk.objectives.vmec_transport_admission', 'DEFAULT_TRANSPORT_METRIC_KEYS'),
    'aggregate_objective_portfolio': ('spectraxgk.objectives.portfolio_contracts', 'aggregate_objective_portfolio'),
    'build_authoritative_wout_candidate_gate': ('spectraxgk.objectives.vmec_candidate_admission', 'build_authoritative_wout_candidate_gate'),
    'build_solved_vmec_candidate_gate': ('spectraxgk.objectives.vmec_candidate_admission', 'build_solved_vmec_candidate_gate'),
    'build_wout_reproducibility_gate': ('spectraxgk.objectives.vmec_candidate_admission', 'build_wout_reproducibility_gate'),
    'build_nonlinear_campaign_admission_report': ('spectraxgk.diagnostics.stellarator_transport_reports', 'build_nonlinear_campaign_admission_report'),
    'build_nonlinear_landscape_admission_report': ('spectraxgk.diagnostics.stellarator_transport_reports', 'build_nonlinear_landscape_admission_report'),
    'build_nonlinear_audit_redesign_report': ('spectraxgk.diagnostics.stellarator_transport_reports', 'build_nonlinear_audit_redesign_report'),
    'build_reduced_nonlinear_audit_prelaunch_report': ('spectraxgk.diagnostics.stellarator_transport_reports', 'build_reduced_nonlinear_audit_prelaunch_report'),
    'build_transport_admission_report': ('spectraxgk.objectives.vmec_transport_admission', 'build_transport_admission_report'),
    'boundary_spec_record': ('spectraxgk.objectives.vmec_transport_gradient', 'boundary_spec_record'),
    'boundary_chain_accepted_parameter_indices': ('spectraxgk.objectives.vmec_transport_line_search', 'boundary_chain_accepted_parameter_indices'),
    'boundary_chain_summary_from_probe': ('spectraxgk.geometry.vmec_boundary_chain', 'boundary_chain_summary_from_probe'),
    'build_boundary_chain_collection_summary': ('spectraxgk.geometry.vmec_boundary_chain', 'build_boundary_chain_collection_summary'),
    'build_boundary_chain_summary': ('spectraxgk.geometry.vmec_boundary_chain', 'build_boundary_chain_summary'),
    'candidate_transport_metric': ('spectraxgk.objectives.vmec_transport_admission', 'candidate_transport_metric'),
    'final_iota_profiles_from_vmec_result': ('spectraxgk.objectives.vmec_candidate_admission', 'final_iota_profiles_from_vmec_result'),
    'objective_portfolio_sensitivity_report': ('spectraxgk.objectives.portfolio_sensitivity', 'objective_portfolio_sensitivity_report'),
    'portfolio_objective_weight_vector': ('spectraxgk.objectives.portfolio_contracts', 'portfolio_objective_weight_vector'),
    'portfolio_sample_weight_tensor': ('spectraxgk.objectives.portfolio_contracts', 'portfolio_sample_weight_tensor'),
    'projected_line_search_input_manifest': ('spectraxgk.objectives.vmec_transport_line_search', 'projected_line_search_input_manifest'),
    'reduced_portfolio_artifact_guard_report': ('spectraxgk.objectives.portfolio_artifacts', 'reduced_portfolio_artifact_guard_report'),
    'validate_objective_portfolio_contract': ('spectraxgk.objectives.portfolio_contracts', 'validate_objective_portfolio_contract'),
    'ZONAL_FLOW_OBJECTIVE_NAMES': ('spectraxgk.objectives.zonal', 'ZONAL_FLOW_OBJECTIVE_NAMES'),
    'ZonalFlowObjectiveConfig': ('spectraxgk.objectives.zonal', 'ZonalFlowObjectiveConfig'),
    'zonal_flow_objective_artifact_from_records': ('spectraxgk.objectives.zonal', 'zonal_flow_objective_artifact_from_records'),
    'zonal_flow_objective_rows': ('spectraxgk.objectives.zonal', 'zonal_flow_objective_rows'),
    'zonal_flow_objective_sensitivity_report': ('spectraxgk.objectives.zonal', 'zonal_flow_objective_sensitivity_report'),
    'zonal_flow_reduced_objective': ('spectraxgk.objectives.zonal', 'zonal_flow_reduced_objective'),
    'SOLVER_GEOMETRY_PARAMETER_NAMES': ('spectraxgk.objectives.solver_gradients', 'SOLVER_GEOMETRY_PARAMETER_NAMES'),
    'SOLVER_OBJECTIVE_NAMES': ('spectraxgk.objectives.solver_gradients', 'SOLVER_OBJECTIVE_NAMES'),
    'SolverScalarObjective': ('spectraxgk.objectives.solver_gradients', 'SolverScalarObjective'),
    'VMEC_BOOZER_FREQUENCY_OBJECTIVE_NAMES': ('spectraxgk.objectives.solver_gradients', 'VMEC_BOOZER_FREQUENCY_OBJECTIVE_NAMES'),
    'VMEC_BOOZER_NONLINEAR_WINDOW_OBJECTIVE_NAMES': ('spectraxgk.objectives.solver_gradients', 'VMEC_BOOZER_NONLINEAR_WINDOW_OBJECTIVE_NAMES'),
    'VMEC_BOOZER_QUASILINEAR_OBJECTIVE_NAMES': ('spectraxgk.objectives.solver_gradients', 'VMEC_BOOZER_QUASILINEAR_OBJECTIVE_NAMES'),
    'VMEC_BOOZER_STATE_PARAMETER_FAMILIES': ('spectraxgk.objectives.solver_gradients', 'VMEC_BOOZER_STATE_PARAMETER_FAMILIES'),
    'VMEC_BOOZER_STATE_PARAMETER_NAMES': ('spectraxgk.objectives.solver_gradients', 'VMEC_BOOZER_STATE_PARAMETER_NAMES'),
    'default_solver_geometry_design_params': ('spectraxgk.objectives.solver_gradients', 'default_solver_geometry_design_params'),
    'dominant_eigenvalue_branch_locality_report': ('spectraxgk.objectives.solver_gradients', 'dominant_eigenvalue_branch_locality_report'),
    'dominant_real_eigenvalue': ('spectraxgk.objectives.solver_gradients', 'dominant_real_eigenvalue'),
    'linear_solver_geometry_gradient_report': ('spectraxgk.objectives.solver_gradients', 'linear_solver_geometry_gradient_report'),
    'mode21_vmec_boozer_linear_frequency_gradient_report': ('spectraxgk.objectives.solver_gradients', 'mode21_vmec_boozer_linear_frequency_gradient_report'),
    'mode21_vmec_boozer_nonlinear_window_gradient_report': ('spectraxgk.objectives.solver_gradients', 'mode21_vmec_boozer_nonlinear_window_gradient_report'),
    'mode21_vmec_boozer_quasilinear_gradient_report': ('spectraxgk.objectives.solver_gradients', 'mode21_vmec_boozer_quasilinear_gradient_report'),
    'solver_linear_operator_matrix_from_geometry': ('spectraxgk.objectives.solver_gradients', 'solver_linear_operator_matrix_from_geometry'),
    'solver_objective_branch_gradient_report': ('spectraxgk.objectives.solver_gradients', 'solver_objective_branch_gradient_report'),
    'solver_growth_rate_from_geometry': ('spectraxgk.objectives.solver_gradients', 'solver_growth_rate_from_geometry'),
    'solver_objective_vector_from_geometry': ('spectraxgk.objectives.solver_gradients', 'solver_objective_vector_from_geometry'),
    'solver_grid_options_from_ky_values': ('spectraxgk.objectives.solver_gradients', 'solver_grid_options_from_ky_values'),
    'solver_scalar_objective_from_vector': ('spectraxgk.objectives.solver_gradients', 'solver_scalar_objective_from_vector'),
    'spectrax_transport_objective_tuple': ('spectraxgk.objectives.vmec_transport', 'spectrax_transport_objective_tuple'),
    'select_admitted_transport_candidate': ('spectraxgk.objectives.vmec_transport_admission', 'select_admitted_transport_candidate'),
    'transport_objective_sample_summary': ('spectraxgk.objectives.vmec_transport_admission', 'transport_objective_sample_summary'),
    'build_boundary_transport_gradient_report': ('spectraxgk.objectives.vmec_transport_gradient', 'build_boundary_transport_gradient_report'),
    'select_projected_line_search_candidate': ('spectraxgk.objectives.vmec_transport_line_search', 'select_projected_line_search_candidate'),
    'sparse_descent_direction_from_gradient_report': ('spectraxgk.objectives.vmec_transport_line_search', 'sparse_descent_direction_from_gradient_report'),
    'vmec_jax_transport_growth_branch_locality_report_from_states': ('spectraxgk.objectives.vmec_transport', 'vmec_jax_transport_growth_branch_locality_report_from_states'),
    'vmec_jax_transport_objective_from_state': ('spectraxgk.objectives.vmec_transport', 'vmec_jax_transport_objective_from_state'),
    'write_boundary_transport_gradient_report': ('spectraxgk.objectives.vmec_transport_gradient', 'write_boundary_transport_gradient_report'),
    'solver_ready_geometry_mapping': ('spectraxgk.objectives.solver_gradients', 'solver_ready_geometry_mapping'),
    'vmec_boozer_aggregate_line_search_holdout_report': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_aggregate_line_search_holdout_report'),
    'vmec_boozer_aggregate_scalar_objective_finite_difference_report': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_aggregate_scalar_objective_finite_difference_report'),
    'vmec_boozer_aggregate_scalar_objective_from_state': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_aggregate_scalar_objective_from_state'),
    'vmec_boozer_aggregate_scalar_objective_line_search_report': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_aggregate_scalar_objective_line_search_report'),
    'vmec_boozer_scalar_objective_finite_difference_report': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_scalar_objective_finite_difference_report'),
    'vmec_boozer_scalar_objective_from_state': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_scalar_objective_from_state'),
    'vmec_boozer_scalar_objective_line_search_report': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_scalar_objective_line_search_report'),
    'vmec_boozer_solver_objective_table_from_state': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_solver_objective_table_from_state'),
    'vmec_boozer_solver_objective_table_with_metadata_from_state': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_solver_objective_table_with_metadata_from_state'),
    'vmec_boozer_solver_objective_vector_from_state': ('spectraxgk.objectives.solver_gradients', 'vmec_boozer_solver_objective_vector_from_state'),
    'eigenfunction_gate_report': ('spectraxgk.diagnostics.validation_gates', 'eigenfunction_gate_report'),
    'evaluate_scalar_gate': ('spectraxgk.diagnostics.validation_gates', 'evaluate_scalar_gate'),
    'gate_report': ('spectraxgk.diagnostics.validation_gates', 'gate_report'),
    'gate_report_to_dict': ('spectraxgk.diagnostics.validation_gates', 'gate_report_to_dict'),
    'linear_metrics_gate_report': ('spectraxgk.diagnostics.validation_gates', 'linear_metrics_gate_report'),
    'nonlinear_window_gate_report': ('spectraxgk.diagnostics.validation_gates', 'nonlinear_window_gate_report'),
    'observed_order_gate_report': ('spectraxgk.diagnostics.validation_gates', 'observed_order_gate_report'),
    'zonal_response_gate_report': ('spectraxgk.diagnostics.validation_gates', 'zonal_response_gate_report'),
    'normalize_eigenfunction': ('spectraxgk.diagnostics.modes', 'normalize_eigenfunction'),
    'run_linear_scan': ('spectraxgk.workflows.linear', 'run_linear_scan'),
    'run_scan_and_mode': ('spectraxgk.workflows.linear', 'run_scan_and_mode'),
    'ModeSelection': ('spectraxgk.diagnostics.analysis', 'ModeSelection'),
    'extract_mode': ('spectraxgk.diagnostics.analysis', 'extract_mode'),
    'extract_mode_time_series': ('spectraxgk.diagnostics.analysis', 'extract_mode_time_series'),
    'extract_eigenfunction': ('spectraxgk.diagnostics.analysis', 'extract_eigenfunction'),
    'select_ky_index': ('spectraxgk.diagnostics.analysis', 'select_ky_index'),
    'cyclone_reference_figure': ('spectraxgk.artifacts.plotting', 'cyclone_reference_figure'),
    'cyclone_comparison_figure': ('spectraxgk.artifacts.plotting', 'cyclone_comparison_figure'),
    'etg_trend_figure': ('spectraxgk.artifacts.plotting', 'etg_trend_figure'),
    'growth_rate_heatmap': ('spectraxgk.artifacts.plotting', 'growth_rate_heatmap'),
    'growth_fit_figure': ('spectraxgk.artifacts.plotting', 'growth_fit_figure'),
    'linear_validation_figure': ('spectraxgk.artifacts.plotting', 'linear_validation_figure'),
    'LinearValidationPanel': ('spectraxgk.artifacts.plotting', 'LinearValidationPanel'),
    'MultiReferenceValidationPanel': ('spectraxgk.artifacts.plotting', 'MultiReferenceValidationPanel'),
    'ReferenceSeries': ('spectraxgk.artifacts.plotting', 'ReferenceSeries'),
    'linear_validation_multi_reference_figure': ('spectraxgk.artifacts.plotting', 'linear_validation_multi_reference_figure'),
    'scan_multi_reference_figure': ('spectraxgk.artifacts.plotting', 'scan_multi_reference_figure'),
    'scan_comparison_figure': ('spectraxgk.artifacts.plotting', 'scan_comparison_figure'),
    'set_plot_style': ('spectraxgk.artifacts.plotting', 'set_plot_style'),
}

def __getattr__(name: str) -> Any:
    """Lazily resolve public API exports from their owning modules."""

    try:
        module_name, attr_name = _EXPORT_TARGETS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(import_module(module_name), attr_name)
    globals()[name] = value
    return value

def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
