"""Public geometry API exports."""

from spectraxgk.geometry import SAlphaGeometry, build_flux_tube_geometry
from spectraxgk.geometry.differentiable import (
    booz_xform_flux_tube_mapping_from_inputs,
    booz_xform_flux_tube_sensitivity_report,
    booz_xform_spectral_sensitivity_report,
    discover_differentiable_geometry_backends,
    evaluate_boozer_bmag_on_field_line,
    finite_difference_jacobian,
    flux_tube_geometry_from_mapping,
    flux_tube_geometry_from_vmec_boozer_state,
    flux_tube_geometry_observables,
    geometry_inverse_design_report,
    geometry_observable_names,
    geometry_sensitivity_report,
    vmec_jax_boozer_equal_arc_core_profiles_from_state,
    vmec_jax_boozer_flux_tube_sensitivity_report,
    vmec_jax_field_line_tensor_sensitivity_report,
    vmec_jax_flux_tube_array_parity_report,
    vmec_jax_flux_tube_mapping_from_state,
    vmec_jax_flux_tube_sensitivity_report,
    vmec_jax_metric_tensor_sensitivity_report,
    vmec_boundary_aspect_sensitivity_report,
    vmec_field_line_tensor_observable_names,
    vmec_metric_tensor_observable_names,
)
from spectraxgk.core.velocity import J_l_all, gamma0
from spectraxgk.geometry.vmec_boundary_chain import (
    boundary_chain_summary_from_probe,
    build_boundary_chain_collection_summary,
    build_boundary_chain_summary,
)

__all__ = [
    "SAlphaGeometry",
    "build_flux_tube_geometry",
    "booz_xform_flux_tube_mapping_from_inputs",
    "booz_xform_flux_tube_sensitivity_report",
    "booz_xform_spectral_sensitivity_report",
    "discover_differentiable_geometry_backends",
    "evaluate_boozer_bmag_on_field_line",
    "finite_difference_jacobian",
    "flux_tube_geometry_from_mapping",
    "flux_tube_geometry_from_vmec_boozer_state",
    "flux_tube_geometry_observables",
    "geometry_inverse_design_report",
    "geometry_observable_names",
    "geometry_sensitivity_report",
    "vmec_jax_boozer_equal_arc_core_profiles_from_state",
    "vmec_jax_boozer_flux_tube_sensitivity_report",
    "vmec_jax_field_line_tensor_sensitivity_report",
    "vmec_jax_flux_tube_array_parity_report",
    "vmec_jax_flux_tube_mapping_from_state",
    "vmec_jax_flux_tube_sensitivity_report",
    "vmec_jax_metric_tensor_sensitivity_report",
    "vmec_boundary_aspect_sensitivity_report",
    "vmec_field_line_tensor_observable_names",
    "vmec_metric_tensor_observable_names",
    "J_l_all",
    "gamma0",
    "boundary_chain_summary_from_probe",
    "build_boundary_chain_collection_summary",
    "build_boundary_chain_summary",
]
