
blank_issues_enabled: false
contact_links:
  - name: Questions / Usage Help
    url: https://github.com/uwplasma/SPECTRAX-GK/discussions
    about: Ask general questions or share ideas in Discussions.
