"""SPECTRAX-GK: a JAX gyrokinetic solver with Hermite-Laguerre velocity space."""

from spectraxgk._version import __version__
from spectraxgk.config import (
    CycloneBaseCase,
    ETGBaseCase,
    GridConfig,
    KineticElectronBaseCase,
    KBMBaseCase,
    TEMBaseCase,
    TimeConfig,
)
from spectraxgk.geometry import SAlphaGeometry, build_flux_tube_geometry
from spectraxgk.geometry.differentiable import (
    discover_differentiable_geometry_backends,
    finite_difference_jacobian,
    flux_tube_geometry_from_mapping,
    flux_tube_geometry_observables,
    geometry_inverse_design_report,
    geometry_observable_names,
    geometry_sensitivity_report,
)
from spectraxgk.gyroaverage import J_l_all, gamma0
from spectraxgk.io import (
    load_case_from_toml,
    load_krylov_from_toml,
    load_linear_terms_from_toml,
    load_runtime_from_toml,
)
from spectraxgk.normalization import (
    DiagnosticNorm,
    NormalizationContract,
    apply_diagnostic_normalization,
    get_normalization_contract,
)
from spectraxgk.runtime import (
    RuntimeLinearResult,
    RuntimeLinearScanResult,
    build_runtime_linear_params,
    build_runtime_linear_terms,
    build_runtime_term_config,
    run_linear_case,
    run_nonlinear_case,
    run_runtime_linear,
    run_runtime_nonlinear,
    run_runtime_scan,
)
from spectraxgk.runtime_config import (
    RuntimeCollisionConfig,
    RuntimeConfig,
    RuntimeNormalizationConfig,
    RuntimeOutputConfig,
    RuntimePhysicsConfig,
    RuntimeSpeciesConfig,
    RuntimeTermsConfig,
)
from spectraxgk.operators import hermite_streaming
from spectraxgk.linear import (
    LinearCache,
    LinearParams,
    LinearTerms,
    build_linear_cache,
    integrate_linear,
    linear_terms_to_term_config,
    linear_rhs,
    linear_rhs_cached,
    term_config_to_linear_terms,
)
from spectraxgk.linear_krylov import KrylovConfig, dominant_eigenpair, dominant_eigenvalue
from spectraxgk.nonlinear import (
    IMEXLinearOperator,
    build_nonlinear_imex_operator,
    integrate_nonlinear,
    integrate_nonlinear_cached,
    integrate_nonlinear_gx_diagnostics,
    nonlinear_rhs_cached,
)
from spectraxgk.runners import integrate_linear_from_config, integrate_nonlinear_from_config
from spectraxgk.species import Species, build_linear_params
from spectraxgk.analysis import (
    ModeSelection,
    extract_mode,
    extract_mode_time_series,
    extract_eigenfunction,
    fit_growth_rate,
    fit_growth_rate_auto,
    gx_growth_rate_from_phi,
    select_fit_window,
    select_ky_index,
)
from spectraxgk.benchmarks import (
    CycloneComparison,
    CycloneReference,
    CycloneRunResult,
    CycloneScanResult,
    LinearRunResult,
    LinearScanResult,
    compare_cyclone_to_reference,
    load_cyclone_reference,
    load_cyclone_reference_kinetic,
    load_etg_reference,
    load_kbm_reference,
    load_tem_reference,
    run_etg_linear,
    run_etg_scan,
    run_kbm_beta_scan,
    run_kbm_scan,
    run_kinetic_linear,
    run_kinetic_scan,
    run_tem_linear,
    run_tem_scan,
    run_cyclone_linear,
    run_cyclone_scan,
)
from spectraxgk.validation_gates import (
    BranchContinuationMetrics,
    GateReport,
    LateTimeLinearMetrics,
    NonlinearWindowMetrics,
    ScalarGateResult,
    ZonalFlowResponseMetrics,
    branch_continuity_gate_report,
    eigenfunction_gate_report,
    evaluate_scalar_gate,
    gate_report,
    gate_report_to_dict,
    linear_metrics_gate_report,
    nonlinear_window_gate_report,
    observed_order_gate_report,
    zonal_response_gate_report,
)
from spectraxgk.benchmarking import (
    ScanAndModeResult,
    branch_continuity_metrics,
    normalize_eigenfunction,
    run_linear_scan,
    run_scan_and_mode,
)
from spectraxgk.autodiff_validation import covariance_diagnostics
from spectraxgk.parallel import batch_map, ky_scan_batches
from spectraxgk.plotting import (
    cyclone_comparison_figure,
    cyclone_reference_figure,
    etg_trend_figure,
    growth_rate_heatmap,
    growth_fit_figure,
    linear_validation_figure,
    LinearValidationPanel,
    MultiReferenceValidationPanel,
    ReferenceSeries,
    linear_validation_multi_reference_figure,
    scan_multi_reference_figure,
    scan_comparison_figure,
    set_plot_style,
)
from spectraxgk.diffrax_integrators import (
    integrate_linear_diffrax,
    integrate_linear_diffrax_streaming,
    integrate_nonlinear_diffrax,
)
from spectraxgk.sharded_integrators import integrate_linear_sharded, integrate_nonlinear_sharded
from spectraxgk.gx_integrators import ExplicitTimeConfig, GXTimeConfig, integrate_linear_gx, integrate_linear_gx_diagnostics
from spectraxgk.diagnostics import GXDiagnostics, SimulationDiagnostics

LinearExplicitTimeConfig = ExplicitTimeConfig
integrate_linear_explicit = integrate_linear_gx
integrate_linear_explicit_diagnostics = integrate_linear_gx_diagnostics
integrate_nonlinear_diagnostics = integrate_nonlinear_gx_diagnostics
growth_rate_from_phi = gx_growth_rate_from_phi

__all__ = [
    "__version__",
    "CycloneBaseCase",
    "ETGBaseCase",
    "GridConfig",
    "KineticElectronBaseCase",
    "KBMBaseCase",
    "TEMBaseCase",
    "TimeConfig",
    "SAlphaGeometry",
    "build_flux_tube_geometry",
    "discover_differentiable_geometry_backends",
    "finite_difference_jacobian",
    "flux_tube_geometry_from_mapping",
    "flux_tube_geometry_observables",
    "geometry_inverse_design_report",
    "geometry_observable_names",
    "geometry_sensitivity_report",
    "J_l_all",
    "gamma0",
    "load_case_from_toml",
    "load_krylov_from_toml",
    "load_linear_terms_from_toml",
    "load_runtime_from_toml",
    "DiagnosticNorm",
    "NormalizationContract",
    "get_normalization_contract",
    "apply_diagnostic_normalization",
    "RuntimeConfig",
    "RuntimeSpeciesConfig",
    "RuntimePhysicsConfig",
    "RuntimeCollisionConfig",
    "RuntimeNormalizationConfig",
    "RuntimeOutputConfig",
    "RuntimeTermsConfig",
    "RuntimeLinearResult",
    "RuntimeLinearScanResult",
    "build_runtime_linear_params",
    "build_runtime_linear_terms",
    "build_runtime_term_config",
    "run_linear_case",
    "run_nonlinear_case",
    "run_runtime_linear",
    "run_runtime_nonlinear",
    "run_runtime_scan",
    "hermite_streaming",
    "LinearParams",
    "LinearTerms",
    "LinearCache",
    "build_linear_cache",
    "linear_terms_to_term_config",
    "term_config_to_linear_terms",
    "linear_rhs",
    "linear_rhs_cached",
    "integrate_linear",
    "KrylovConfig",
    "dominant_eigenpair",
    "dominant_eigenvalue",
    "integrate_linear_diffrax",
    "integrate_linear_diffrax_streaming",
    "integrate_linear_sharded",
    "integrate_nonlinear_sharded",
    "integrate_nonlinear",
    "integrate_nonlinear_cached",
    "integrate_nonlinear_gx_diagnostics",
    "integrate_nonlinear_diagnostics",
    "integrate_nonlinear_diffrax",
    "build_nonlinear_imex_operator",
    "IMEXLinearOperator",
    "GXTimeConfig",
    "ExplicitTimeConfig",
    "LinearExplicitTimeConfig",
    "integrate_linear_gx",
    "integrate_linear_explicit",
    "integrate_linear_gx_diagnostics",
    "integrate_linear_explicit_diagnostics",
    "GXDiagnostics",
    "SimulationDiagnostics",
    "nonlinear_rhs_cached",
    "integrate_linear_from_config",
    "integrate_nonlinear_from_config",
    "Species",
    "build_linear_params",
    "load_cyclone_reference",
    "load_cyclone_reference_kinetic",
    "load_etg_reference",
    "load_kbm_reference",
    "load_tem_reference",
    "fit_growth_rate",
    "fit_growth_rate_auto",
    "gx_growth_rate_from_phi",
    "growth_rate_from_phi",
    "select_fit_window",
    "CycloneReference",
    "CycloneScanResult",
    "CycloneComparison",
    "LinearRunResult",
    "LinearScanResult",
    "run_etg_linear",
    "run_etg_scan",
    "run_kinetic_linear",
    "run_kinetic_scan",
    "run_tem_linear",
    "run_tem_scan",
    "run_kbm_beta_scan",
    "run_kbm_scan",
    "run_cyclone_linear",
    "run_cyclone_scan",
    "ScanAndModeResult",
    "BranchContinuationMetrics",
    "ScalarGateResult",
    "GateReport",
    "LateTimeLinearMetrics",
    "NonlinearWindowMetrics",
    "ZonalFlowResponseMetrics",
    "branch_continuity_gate_report",
    "branch_continuity_metrics",
    "covariance_diagnostics",
    "batch_map",
    "ky_scan_batches",
    "eigenfunction_gate_report",
    "evaluate_scalar_gate",
    "gate_report",
    "gate_report_to_dict",
    "linear_metrics_gate_report",
    "nonlinear_window_gate_report",
    "observed_order_gate_report",
    "zonal_response_gate_report",
    "normalize_eigenfunction",
    "run_linear_scan",
    "run_scan_and_mode",
    "compare_cyclone_to_reference",
    "CycloneRunResult",
    "ModeSelection",
    "extract_mode",
    "extract_mode_time_series",
    "extract_eigenfunction",
    "select_ky_index",
    "cyclone_reference_figure",
    "cyclone_comparison_figure",
    "etg_trend_figure",
    "growth_rate_heatmap",
    "growth_fit_figure",
    "linear_validation_figure",
    "LinearValidationPanel",
    "MultiReferenceValidationPanel",
    "ReferenceSeries",
    "linear_validation_multi_reference_figure",
    "scan_multi_reference_figure",
    "scan_comparison_figure",
    "set_plot_style",
]
