"""SPECTRAX-GK: a JAX gyrokinetic solver with Hermite-Laguerre velocity space."""

from spectraxgk._version import __version__
from spectraxgk.config import CycloneBaseCase, ETGBaseCase, GridConfig, MTMBaseCase, TimeConfig
from spectraxgk.geometry import SAlphaGeometry
from spectraxgk.gyroaverage import J_l_all, gamma0
from spectraxgk.operators import hermite_streaming
from spectraxgk.linear import (
    LinearCache,
    LinearParams,
    build_linear_cache,
    integrate_linear,
    linear_rhs,
    linear_rhs_cached,
)
from spectraxgk.analysis import (
    ModeSelection,
    extract_mode,
    extract_mode_time_series,
    extract_eigenfunction,
    fit_growth_rate,
    fit_growth_rate_auto,
    select_fit_window,
    select_ky_index,
)
from spectraxgk.benchmarks import (
    CycloneComparison,
    CycloneReference,
    CycloneRunResult,
    CycloneScanResult,
    ETGRunResult,
    ETGScanResult,
    MTMRunResult,
    MTMScanResult,
    compare_cyclone_to_reference,
    load_cyclone_reference,
    run_etg_linear,
    run_etg_scan,
    run_mtm_linear,
    run_mtm_scan,
    run_cyclone_linear,
    run_cyclone_scan,
)
from spectraxgk.plotting import (
    cyclone_comparison_figure,
    cyclone_reference_figure,
    etg_trend_figure,
    linear_validation_figure,
    LinearValidationPanel,
    mtm_trend_figure,
    set_plot_style,
)

__all__ = [
    "__version__",
    "CycloneBaseCase",
    "ETGBaseCase",
    "GridConfig",
    "MTMBaseCase",
    "TimeConfig",
    "SAlphaGeometry",
    "J_l_all",
    "gamma0",
    "hermite_streaming",
    "LinearParams",
    "LinearCache",
    "build_linear_cache",
    "linear_rhs",
    "linear_rhs_cached",
    "integrate_linear",
    "load_cyclone_reference",
    "fit_growth_rate",
    "fit_growth_rate_auto",
    "select_fit_window",
    "CycloneReference",
    "CycloneScanResult",
    "CycloneComparison",
    "ETGRunResult",
    "ETGScanResult",
    "MTMRunResult",
    "MTMScanResult",
    "run_etg_linear",
    "run_etg_scan",
    "run_mtm_linear",
    "run_mtm_scan",
    "run_cyclone_linear",
    "run_cyclone_scan",
    "compare_cyclone_to_reference",
    "CycloneRunResult",
    "ModeSelection",
    "extract_mode",
    "extract_mode_time_series",
    "extract_eigenfunction",
    "select_ky_index",
    "cyclone_reference_figure",
    "cyclone_comparison_figure",
    "etg_trend_figure",
    "linear_validation_figure",
    "LinearValidationPanel",
    "mtm_trend_figure",
    "set_plot_style",
]
