"""SPECTRAX-GK: a JAX gyrokinetic solver with Hermite-Laguerre velocity space."""

from spectraxgk._version import __version__
from spectraxgk.config import (
    CycloneBaseCase,
    ETGBaseCase,
    GridConfig,
    KineticElectronBaseCase,
    KBMBaseCase,
    TEMBaseCase,
    TimeConfig,
)
from spectraxgk.geometry import SAlphaGeometry
from spectraxgk.gyroaverage import J_l_all, gamma0
from spectraxgk.operators import hermite_streaming
from spectraxgk.linear import (
    LinearCache,
    LinearParams,
    LinearTerms,
    build_linear_cache,
    integrate_linear,
    linear_rhs,
    linear_rhs_cached,
)
from spectraxgk.nonlinear import integrate_nonlinear, integrate_nonlinear_cached, nonlinear_rhs_cached
from spectraxgk.species import Species, build_linear_params
from spectraxgk.analysis import (
    ModeSelection,
    extract_mode,
    extract_mode_time_series,
    extract_eigenfunction,
    fit_growth_rate,
    fit_growth_rate_auto,
    select_fit_window,
    select_ky_index,
)
from spectraxgk.benchmarks import (
    CycloneComparison,
    CycloneReference,
    CycloneRunResult,
    CycloneScanResult,
    LinearRunResult,
    LinearScanResult,
    compare_cyclone_to_reference,
    load_cyclone_reference,
    load_cyclone_reference_kinetic,
    load_etg_reference,
    load_kbm_reference,
    load_tem_reference,
    run_etg_linear,
    run_etg_scan,
    run_kbm_beta_scan,
    run_kinetic_linear,
    run_kinetic_scan,
    run_tem_linear,
    run_tem_scan,
    run_cyclone_linear,
    run_cyclone_scan,
)
from spectraxgk.plotting import (
    cyclone_comparison_figure,
    cyclone_reference_figure,
    etg_trend_figure,
    growth_rate_heatmap,
    linear_validation_figure,
    LinearValidationPanel,
    scan_comparison_figure,
    set_plot_style,
)
from spectraxgk.diffrax_integrators import integrate_linear_diffrax, integrate_nonlinear_diffrax

__all__ = [
    "__version__",
    "CycloneBaseCase",
    "ETGBaseCase",
    "GridConfig",
    "KineticElectronBaseCase",
    "KBMBaseCase",
    "TEMBaseCase",
    "TimeConfig",
    "SAlphaGeometry",
    "J_l_all",
    "gamma0",
    "hermite_streaming",
    "LinearParams",
    "LinearTerms",
    "LinearCache",
    "build_linear_cache",
    "linear_rhs",
    "linear_rhs_cached",
    "integrate_linear",
    "integrate_linear_diffrax",
    "integrate_nonlinear",
    "integrate_nonlinear_cached",
    "integrate_nonlinear_diffrax",
    "nonlinear_rhs_cached",
    "Species",
    "build_linear_params",
    "load_cyclone_reference",
    "load_cyclone_reference_kinetic",
    "load_etg_reference",
    "load_kbm_reference",
    "load_tem_reference",
    "fit_growth_rate",
    "fit_growth_rate_auto",
    "select_fit_window",
    "CycloneReference",
    "CycloneScanResult",
    "CycloneComparison",
    "LinearRunResult",
    "LinearScanResult",
    "run_etg_linear",
    "run_etg_scan",
    "run_kinetic_linear",
    "run_kinetic_scan",
    "run_tem_linear",
    "run_tem_scan",
    "run_kbm_beta_scan",
    "run_cyclone_linear",
    "run_cyclone_scan",
    "compare_cyclone_to_reference",
    "CycloneRunResult",
    "ModeSelection",
    "extract_mode",
    "extract_mode_time_series",
    "extract_eigenfunction",
    "select_ky_index",
    "cyclone_reference_figure",
    "cyclone_comparison_figure",
    "etg_trend_figure",
    "growth_rate_heatmap",
    "linear_validation_figure",
    "LinearValidationPanel",
    "scan_comparison_figure",
    "set_plot_style",
]
