[[species]]
name = "ion"
charge = 1.0
mass = 1.0
density = 1.0
temperature = 1.0
tprim = 2.49
fprim = 0.8
kinetic = true

[grid]
Nx = 64
Ny = 64
Nz = 24
Lx = 62.8
Ly = 62.8
boundary = "linked"
y0 = 28.2
ntheta = 24
nperiod = 1

[time]
t_max = 5.0
dt = 0.05
method = "rk3"
sample_stride = 1
diagnostics_stride = 1
use_diffrax = false
fixed_dt = true
cfl = 0.9
cfl_fac = 1.0
gx_real_fft = true
laguerre_nonlinear_mode = "grid"

[geometry]
model = "s-alpha"
q = 1.4
s_hat = 0.8
epsilon = 0.18
R0 = 2.77778

[init]
init_field = "density"
init_amp = 1.0e-3
init_single = false
random_seed = 22
gaussian_init = false
kpar_init = 0.0

[physics]
electrostatic = true
electromagnetic = false
adiabatic_electrons = true
tau_e = 1.0
nonlinear = true
beta = 0.0
collisions = false
hypercollisions = true

[collisions]
nu_hermite = 0.0
nu_laguerre = 0.0
D_hyper = 0.05
p_hyper = 2.0
p_hyper_m = 4.0
p_hyper_kperp = 2.0
hypercollisions_const = 0.0
hypercollisions_kz = 1.0
damp_ends_amp = 0.0
damp_ends_widthfrac = 0.0

[terms]
streaming = 1.0
mirror = 1.0
curvature = 1.0
gradb = 1.0
diamagnetic = 1.0
collisions = 0.0
hypercollisions = 1.0
hyperdiffusion = 1.0
end_damping = 1.0
nonlinear = 1.0

[normalization]
contract = "cyclone"
diagnostic_norm = "gx"

[run]
ky = 0.03546099290780142
Nl = 4
Nm = 8
