[sim]
mode    = "dg"      # "fourier" or "dg"
backend = "diffrax"          # "eig" or "diffrax"
tmax    = 10.0   # <-- now interpreted as 40 / ω_p (dimensionless)
nt      = 200
nonlinear = true        # << set true for NL, false for linear
dealias_frac = 0.6667   # optional; only used in Fourier-NL

[grid]
L_lambdaD  = 64         # box is 64 Debye lengths long
debye_species = "electrons"   # optional; otherwise first q<0 is used
Nx = 23                 # number of x points (DG) or Fourier modes in the box

[hermite]
N  = 32

[bc]
kind = "periodic"        # for DG; ignored by Fourier

# ---- Species ----
# Electrons: light, warm, small density perturbation at k=1 (i.e. cos(2π x / L))
[[species]]
name           = "electrons"
q              = -1.0
n0             = 1.0
mass_base      = "electron"
mass_multiple  = 1.0
temperature_eV = 1.0       # 1 eV electrons
drift_c        = 0.00
nu0            = 0.0
hyper_p        = 0
collide_cutoff = 3
amplitude      = 1e-3
k              = 0.5
seed_c1        = true

# Ions: heavy, weakly warm, no initial perturbation (neutralizing background)

[[species]]
name           = "ions"
q              = +1.0
n0             = 1.0
mass_base      = "proton"
mass_multiple  = 1.0
temperature_eV = 1.0
drift_c        = 0.00
nu0            = 0.0
hyper_p        = 0
collide_cutoff = 3
amplitude      = 0.0
k              = 0.5
seed_c1        = false

[plot]
nv         = 257
vmin_c     = -0.1
vmax_c     = 0.1
fps        = 30
dpi        = 150
no_show    = false
fig_width = 10.0        # total width in inches
fig_row_height = 2.2    # height per row in inches (row 1 is energy/Ex,t; each species adds a row)
# save_anim = "out.mp4"   # or "" to disable
