[sim]
mode    = "fourier"      # "fourier" or "dg" (DG stubbed for now)
backend = "diffrax"
tmax    = 10.0
nt      = 401
save_every = 1
nonlinear = false
precision = "x64"        # x64 or x32
solver   = "dopri8"
adaptive = true
rtol     = 1e-6
atol     = 1e-9
# dt only used when adaptive=false (constant step)
# dt       = 0.02

[grid]
Nn  = 32
Nm  = 8
kpar = 1.0
vth  = 1.0
nu   = 0.01
es_drive = true
e_coef = 1.0

[ic]
kind  = "n0_mode"       # or "random"
amp   = 1e-3
phase = 0.0

[paths]
outdir  = "outputs"
outfile = "linear_slab_run.npz"
