[[species]]
name = "ion"
charge = 1.0
mass = 1.0
density = 1.0
temperature = 1.0
tprim = 0.0
fprim = 0.0
nu = 0.0
kinetic = true

[grid]
Nx = 4
Ny = 4
Nz = 8
Lx = 125.66370614359172
Ly = 62.83185307179586
boundary = "periodic"
y0 = 10.0
ntheta = 8
nperiod = 1

[time]
t_max = 2.0
dt = 1.0
method = "rk3"
use_diffrax = false
sample_stride = 1
fixed_dt = true
cfl = 1.0

[geometry]
model = "slab"
s_hat = 1e-8

[init]
init_field = "density"
init_amp = 1.0
gaussian_init = false
init_single = true
kpar_init = 0.0

[physics]
linear = true
nonlinear = false
electrostatic = true
electromagnetic = false
adiabatic_electrons = true
adiabatic_ions = false
tau_e = 1.0
beta = 0.0
collisions = false
hypercollisions = false

[collisions]
damp_ends_amp = 0.0
damp_ends_widthfrac = 0.0

[normalization]
contract = "kinetic"
diagnostic_norm = "gx"

[terms]
streaming = 1.0
mirror = 1.0
curvature = 1.0
gradb = 1.0
diamagnetic = 1.0
collisions = 0.0
hypercollisions = 0.0
hyperdiffusion = 0.0
end_damping = 0.0
apar = 0.0
bpar = 0.0
nonlinear = 0.0

[run]
ky = 0.1
Nl = 3
Nm = 8
solver = "gx_time"
