#!/usr/bin/env python3
"""Build matched multi-sample nonlinear transport optimization campaigns.

The broad nonlinear turbulent-flux optimization claim needs more than one
baseline-to-candidate heat-flux trace.  This tool writes a reproducible matrix
campaign over surfaces, field-line labels, and ky values, then aggregates the
completed matched comparisons.  It writes launch and postprocessing commands;
it does not run simulations by itself.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import shlex
import sys
from typing import Any, Iterable, Mapping, Sequence

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from spectraxgk.artifacts.plotting import set_plot_style  # noqa: E402
from tools.write_external_vmec_holdout_configs import (  # noqa: E402
    _parse_grid,
    _parse_horizons,
    write_configs,
    write_manifest,
)


DEFAULT_SURFACES = "0.45,0.64,0.78"
DEFAULT_ALPHAS = "0.0,pi/4"
DEFAULT_KY_VALUES = "0.10,0.30,0.50"
DEFAULT_GRID = "n64:64:64:40:40"
DEFAULT_HORIZONS = "700,1100,1500"
DEFAULT_WINDOW = (1100.0, 1500.0)
DEFAULT_SEEDS = (31, 32)
DEFAULT_DT_VARIANTS = (0.04,)


def _repo_relative(path: Path | str) -> str:
    raw = Path(path)
    try:
        return raw.resolve().relative_to(ROOT.resolve()).as_posix()
    except (OSError, ValueError):
        return raw.as_posix()


def _json_clean(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _json_clean(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_clean(item) for item in value]
    if isinstance(value, Path):
        return _repo_relative(value)
    return value


def _parse_float_token(raw: str) -> float:
    token = raw.strip().lower().replace("π", "pi")
    if not token:
        raise ValueError("empty float token")
    if token == "pi":
        return float(math.pi)
    if token == "-pi":
        return float(-math.pi)
    if token.startswith("pi/"):
        return float(math.pi / float(token.split("/", 1)[1]))
    if token.startswith("-pi/"):
        return float(-math.pi / float(token.split("/", 1)[1]))
    if "*pi" in token:
        scale = token.split("*pi", 1)[0]
        return float(scale) * float(math.pi)
    return float(token)


def _parse_float_list(raw: str | Sequence[float]) -> tuple[float, ...]:
    if isinstance(raw, str):
        values = tuple(_parse_float_token(item) for item in raw.split(",") if item.strip())
    else:
        values = tuple(float(item) for item in raw)
    if not values:
        raise ValueError("at least one value is required")
    if any(not math.isfinite(value) for value in values):
        raise ValueError("all values must be finite")
    return values


def _value_label(value: float) -> str:
    sign = "m" if value < 0.0 else ""
    return sign + f"{abs(float(value)):.6g}".replace(".", "p")


def _sample_id(torflux: float, alpha: float, ky: float) -> str:
    return f"s{_value_label(torflux)}_a{_value_label(alpha)}_ky{_value_label(ky)}"


def _state_case(prefix: str, state_label: str, sample_id: str) -> str:
    return f"{prefix}_{state_label}_{sample_id}".replace("-", "_")


def _quote_paths(paths: Iterable[Path]) -> str:
    return " ".join(path.as_posix() for path in paths)


def _write_script(
    path: Path,
    commands: Sequence[str],
    *,
    title: str,
    extra_exports: Mapping[str, str] | None = None,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        f"# {title}",
        "# Generated by tools/build_matched_nonlinear_transport_matrix.py.",
        "export PYTHONPATH=src:${PYTHONPATH:-}",
        ': "${DEVICE:=0}"',
    ]
    for key, value in (extra_exports or {}).items():
        lines.append(f"export {key}={value}")
    lines.append("")
    for idx, command in enumerate(commands, start=1):
        lines.extend([f"echo '[{idx}/{len(commands)}] {title}'", command, ""])
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    path.chmod(0o755)


def _load_manifest(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def _final_outputs(written: Sequence[Any], *, horizon: float, grid_label: str) -> list[Path]:
    outputs = [
        item.output_path
        for item in written
        if abs(float(item.horizon) - float(horizon)) < 1.0e-12 and item.grid.label == grid_label
    ]
    if not outputs:
        raise ValueError("no final-horizon outputs were generated")
    return outputs


def _bundle_base(path: Path) -> Path:
    name = path.name
    for suffix in (".out.nc", ".big.nc", ".restart.nc"):
        if name.endswith(suffix):
            return path.with_name(name[: -len(suffix)])
    return path.with_suffix("") if path.suffix == ".nc" else path


def _final_horizon_direct_commands(
    written: Sequence[Any],
    *,
    horizon: float,
    grid_label: str,
) -> list[str]:
    commands: list[str] = []
    for item in written:
        if abs(float(item.horizon) - float(horizon)) > 1.0e-12:
            continue
        if item.grid.label != grid_label:
            continue
        direct_steps = int(round(float(item.horizon) / float(item.dt)))
        output_base = _bundle_base(item.output_path)
        time_tolerance = max(1.0e-9, 2.0 * float(item.dt))
        target_check = (
            "PYTHONPATH=src python3 tools/release/check_nonlinear_output_target.py "
            f"--output {item.output_path.as_posix()} "
            f"--target-time {float(item.horizon):.12g} "
            f"--time-tolerance {time_tolerance:.12g} --quiet"
        )
        lock_file = f"{output_base.as_posix()}.run.lock"
        run_command = (
            "PYTHONPATH=src CUDA_VISIBLE_DEVICES=${DEVICE:-0} "
            "python3 -m spectraxgk.cli run-runtime-nonlinear "
            f"--config {item.path.as_posix()} --steps {direct_steps} --no-progress"
        )
        command = (
            f"lock_file={shlex.quote(lock_file)}; "
            f"if {target_check}; "
            f"then echo skip-target-confirmed {output_base.as_posix()}; "
            "elif command -v flock >/dev/null 2>&1; then "
            f"(flock -n 9 || {{ echo skip-locked {output_base.as_posix()}; exit 0; }}; "
            f"if {target_check}; "
            f"then echo skip-target-confirmed-after-lock {output_base.as_posix()}; "
            f"else {run_command}; fi) 9>\"$lock_file\"; "
            "else lock_dir=${lock_file}.d; "
            "if mkdir \"$lock_dir\" 2>/dev/null; then "
            f"(trap 'rmdir \"$lock_dir\" 2>/dev/null || true' EXIT; "
            f"if {target_check}; "
            f"then echo skip-target-confirmed-after-lock {output_base.as_posix()}; "
            f"else {run_command}; fi); "
            f"else echo skip-locked {output_base.as_posix()}; fi; fi"
        )
        commands.append(command)
    if not commands:
        raise ValueError("no final-horizon direct commands were generated")
    return commands


def _write_state_configs(
    *,
    case: str,
    vmec_file: Path,
    out_dir: Path,
    grid_raw: str,
    horizons_raw: str,
    dt: float,
    ky: float,
    nl: int,
    nm: int,
    torflux: float,
    alpha: float,
    npol: float,
    tprim: float,
    fprim: float,
    nu: float,
    init_amp: float,
    y0: float,
    lx: float,
    ly: float,
    sample_stride: int,
    diagnostics_stride: int,
    baseline_seed: int,
    seed_variants: Sequence[int],
    dt_variants: Sequence[float],
) -> tuple[list[Any], Path, dict[str, Any]]:
    grid = _parse_grid(grid_raw)
    horizons = _parse_horizons(horizons_raw)
    written = write_configs(
        case=case,
        vmec_file=vmec_file,
        out_dir=out_dir,
        grids=(grid,),
        horizons=horizons,
        dt=float(dt),
        ky=float(ky),
        nl=int(nl),
        nm=int(nm),
        torflux=float(torflux),
        alpha=float(alpha),
        npol=float(npol),
        tprim=float(tprim),
        fprim=float(fprim),
        nu=float(nu),
        init_amp=float(init_amp),
        y0=float(y0),
        lx=float(lx),
        ly=float(ly),
        sample_stride=int(sample_stride),
        diagnostics_stride=int(diagnostics_stride),
        baseline_seed=int(baseline_seed),
        seed_variants=tuple(int(seed) for seed in seed_variants),
        dt_variants=tuple(float(value) for value in dt_variants),
    )
    manifest_path = write_manifest(out_dir, written)
    return written, manifest_path, _load_manifest(manifest_path)


def _ensemble_paths(artifact_dir: Path, case: str) -> dict[str, Path]:
    return {
        "output_gate": artifact_dir / f"{case}_output_gate.json",
        "readiness": artifact_dir / f"{case}_readiness.json",
        "ensemble": artifact_dir / f"{case}_ensemble_gate.json",
        "figure": artifact_dir / f"{case}_ensemble_gate.png",
    }


def _state_postprocess_commands(
    *,
    outputs: Sequence[Path],
    artifact_dir: Path,
    case: str,
    tmin: float,
    tmax: float,
    max_mean_rel_spread: float,
    max_combined_sem_rel: float,
    min_samples: int,
    min_window_samples: int,
) -> tuple[dict[str, Path], list[str]]:
    paths = _ensemble_paths(artifact_dir, case)
    outputs_raw = _quote_paths(outputs)
    output_gate = (
        "python3 tools/release/check_nonlinear_runtime_outputs.py "
        f"{outputs_raw} --min-samples {int(min_samples)} --tmin {tmin:.12g} --tmax {tmax:.12g} "
        f"--min-window-samples {int(min_window_samples)} --min-abs-window-mean 0.0001 "
        f"--json-out {paths['output_gate'].as_posix()}"
    )
    ensemble = (
        "python3 tools/build_external_vmec_replicate_ensemble.py "
        f"{outputs_raw} --out-dir {artifact_dir.as_posix()} --case {case}_replicated_nonlinear_window "
        f"--tmin {tmin:.12g} --tmax {tmax:.12g} --artifact-prefix {_repo_relative(artifact_dir)} "
        f"--readiness-json {paths['readiness'].name} --ensemble-json {paths['ensemble'].name} "
        f"--out-png {paths['figure'].name} --max-mean-rel-spread {max_mean_rel_spread:.12g} "
        f"--max-combined-sem-rel {max_combined_sem_rel:.12g}"
    )
    return paths, [output_gate, ensemble]


def build_campaign(args: argparse.Namespace) -> dict[str, Any]:
    surfaces = _parse_float_list(args.surfaces)
    alphas = _parse_float_list(args.alphas)
    ky_values = _parse_float_list(args.ky_values)
    seed_variants = tuple(args.seed_variant or DEFAULT_SEEDS)
    dt_variants = tuple(args.dt_variant or DEFAULT_DT_VARIANTS)
    horizon_values = _parse_horizons(str(args.horizons))
    tmax = float(args.window_tmax)
    if abs(tmax - float(horizon_values[-1])) > 1.0e-12:
        raise ValueError("window-tmax must equal the final generated horizon")
    grid = _parse_grid(str(args.grid))
    out_dir = Path(args.out_dir)
    artifact_dir = Path(args.artifact_dir or (out_dir / "artifacts"))
    out_dir.mkdir(parents=True, exist_ok=True)
    artifact_dir.mkdir(parents=True, exist_ok=True)

    samples: list[dict[str, Any]] = []
    all_staged_commands: list[str] = []
    all_direct_commands: list[str] = []
    all_final_direct_commands: list[str] = []
    all_postprocess_commands: list[str] = []
    comparison_jsons: list[Path] = []

    for torflux in surfaces:
        for alpha in alphas:
            for ky in ky_values:
                sample_id = _sample_id(torflux, alpha, ky)
                sample_dir = out_dir / sample_id
                sample_artifact_dir = artifact_dir / sample_id
                sample_artifact_dir.mkdir(parents=True, exist_ok=True)
                states: dict[str, Any] = {}
                state_ensembles: dict[str, Path] = {}
                for role, vmec_file, state_label in (
                    ("baseline", Path(args.baseline_vmec_file), str(args.baseline_label)),
                    ("candidate", Path(args.candidate_vmec_file), str(args.candidate_label)),
                ):
                    case = _state_case(str(args.case_prefix), state_label, sample_id)
                    state_dir = sample_dir / state_label
                    written, state_manifest_path, state_manifest = _write_state_configs(
                        case=case,
                        vmec_file=vmec_file,
                        out_dir=state_dir,
                        grid_raw=str(args.grid),
                        horizons_raw=str(args.horizons),
                        dt=float(args.dt),
                        ky=ky,
                        nl=int(args.Nl),
                        nm=int(args.Nm),
                        torflux=torflux,
                        alpha=alpha,
                        npol=float(args.npol),
                        tprim=float(args.tprim),
                        fprim=float(args.fprim),
                        nu=float(args.nu),
                        init_amp=float(args.init_amp),
                        y0=float(args.y0),
                        lx=float(args.Lx),
                        ly=float(args.Ly),
                        sample_stride=int(args.sample_stride),
                        diagnostics_stride=int(args.diagnostics_stride),
                        baseline_seed=int(args.baseline_seed),
                        seed_variants=seed_variants,
                        dt_variants=dt_variants,
                    )
                    outputs = _final_outputs(written, horizon=tmax, grid_label=grid.label)
                    ensemble_paths, postprocess = _state_postprocess_commands(
                        outputs=outputs,
                        artifact_dir=sample_artifact_dir,
                        case=case,
                        tmin=float(args.window_tmin),
                        tmax=float(args.window_tmax),
                        max_mean_rel_spread=float(args.max_mean_rel_spread),
                        max_combined_sem_rel=float(args.max_combined_sem_rel),
                        min_samples=int(args.min_samples),
                        min_window_samples=int(args.min_window_samples),
                    )
                    all_postprocess_commands.extend(postprocess)
                    all_staged_commands.extend(state_manifest["staged_ladder_skip_existing_commands"])
                    all_direct_commands.extend(state_manifest["direct_full_horizon_skip_existing_launch_commands"])
                    all_final_direct_commands.extend(
                        _final_horizon_direct_commands(
                            written,
                            horizon=tmax,
                            grid_label=grid.label,
                        )
                    )
                    state_ensembles[role] = ensemble_paths["ensemble"]
                    states[role] = {
                        "label": state_label,
                        "case": case,
                        "vmec_file": _repo_relative(vmec_file),
                        "state_manifest": _repo_relative(state_manifest_path),
                        "final_outputs": [_repo_relative(path) for path in outputs],
                        "postprocess": {key: _repo_relative(path) for key, path in ensemble_paths.items()},
                    }

                comparison_base = sample_artifact_dir / f"{args.case_prefix}_{sample_id}_matched_comparison"
                comparison_json = comparison_base.with_suffix(".json")
                comparison_png = comparison_base.with_suffix(".png")
                comparison_jsons.append(comparison_json)
                comparison_command = (
                    "python3 tools/build_matched_nonlinear_transport_comparison.py "
                    f"--baseline-ensemble {state_ensembles['baseline'].as_posix()} "
                    f"--candidate-ensemble {state_ensembles['candidate'].as_posix()} "
                    f"--case {args.case_prefix}_{sample_id}_matched_nonlinear_transport "
                    f"--min-relative-reduction {float(args.min_relative_reduction):.12g} "
                    f"--out-json {comparison_json.as_posix()} --out-figure {comparison_png.as_posix()}"
                )
                all_postprocess_commands.append(comparison_command)
                samples.append(
                    {
                        "sample_id": sample_id,
                        "surface_torflux": torflux,
                        "alpha": alpha,
                        "ky": ky,
                        "states": states,
                        "comparison": {
                            "json": _repo_relative(comparison_json),
                            "figure": _repo_relative(comparison_png),
                            "command": comparison_command,
                        },
                    }
                )

    staged_script = out_dir / "run_matrix_staged_ladder_skip_existing.sh"
    direct_script = out_dir / "run_matrix_direct_full_horizon_skip_existing.sh"
    final_direct_script = out_dir / "run_matrix_final_horizon_direct_skip_existing.sh"
    postprocess_script = out_dir / "run_matrix_postprocess.sh"
    _write_script(staged_script, all_staged_commands, title="matched nonlinear transport matrix staged ladder")
    _write_script(direct_script, all_direct_commands, title="matched nonlinear transport matrix direct full horizon")
    _write_script(
        final_direct_script,
        all_final_direct_commands,
        title="matched nonlinear transport matrix final horizon direct launches",
    )
    gpu_split_scripts: list[Path] = []
    gpu_splits = int(args.gpu_splits)
    if gpu_splits < 1:
        raise ValueError("--gpu-splits must be >= 1")
    for gpu in range(gpu_splits):
        if gpu_splits == 1:
            break
        script = out_dir / f"run_matrix_final_horizon_gpu{gpu}.sh"
        gpu_split_scripts.append(script)
        _write_script(
            script,
            all_final_direct_commands[gpu::gpu_splits],
            title=f"matched nonlinear transport matrix final horizon GPU {gpu}",
            extra_exports={"DEVICE": str(gpu)},
        )
    report_json = artifact_dir / f"{args.case_prefix}_matrix_report.json"
    report_png = artifact_dir / f"{args.case_prefix}_matrix_report.png"
    manifest_path = out_dir / "matched_transport_matrix_manifest.json"
    report_command = (
        "python3 tools/build_matched_nonlinear_transport_matrix.py report "
        f"--matrix-manifest {manifest_path.as_posix()} --out-json {report_json.as_posix()} "
        f"--out-figure {report_png.as_posix()} --min-pass-fraction {float(args.min_pass_fraction):.12g} "
        f"--min-mean-relative-reduction {float(args.min_mean_relative_reduction):.12g}"
    )
    _write_script(postprocess_script, [*all_postprocess_commands, report_command], title="matched nonlinear transport matrix postprocess")

    manifest = {
        "kind": "matched_nonlinear_transport_matrix_campaign",
        "claim_level": "multi_surface_alpha_ky_launch_contract_not_transport_promotion",
        "case_prefix": str(args.case_prefix),
        "config": {
            "surfaces": list(surfaces),
            "alphas": list(alphas),
            "ky_values": list(ky_values),
            "sample_count": len(samples),
            "grid": str(args.grid),
            "horizons": list(horizon_values),
            "window": {"tmin": float(args.window_tmin), "tmax": float(args.window_tmax)},
            "dt": float(args.dt),
            "seed_variants": list(seed_variants),
            "dt_variants": list(dt_variants),
            "min_relative_reduction": float(args.min_relative_reduction),
            "min_pass_fraction": float(args.min_pass_fraction),
            "min_mean_relative_reduction": float(args.min_mean_relative_reduction),
            "max_mean_rel_spread": float(args.max_mean_rel_spread),
            "max_combined_sem_rel": float(args.max_combined_sem_rel),
            "gpu_splits": int(args.gpu_splits),
            "final_horizon_launch_locking": "per-output flock with mkdir fallback",
        },
        "coverage_gate": {
            "min_surfaces": 3,
            "min_alphas": 2,
            "min_ky_values": 3,
            "passed": len(set(surfaces)) >= 3 and len(set(alphas)) >= 2 and len(set(ky_values)) >= 3,
        },
        "states": {
            "baseline": {"label": str(args.baseline_label), "vmec_file": _repo_relative(Path(args.baseline_vmec_file))},
            "candidate": {"label": str(args.candidate_label), "vmec_file": _repo_relative(Path(args.candidate_vmec_file))},
        },
        "samples": samples,
        "launch_scripts": {
            "staged_ladder_skip_existing": _repo_relative(staged_script),
            "direct_full_horizon_skip_existing": _repo_relative(direct_script),
            "final_horizon_direct_skip_existing": _repo_relative(final_direct_script),
            "final_horizon_gpu_splits": [_repo_relative(path) for path in gpu_split_scripts],
            "postprocess": _repo_relative(postprocess_script),
        },
        "aggregate_report": {"json": _repo_relative(report_json), "figure": _repo_relative(report_png), "command": report_command},
        "notes": [
            "Run the staged ladder script for restart-continuation launches, or the direct script to start every final-horizon replicate from t=0.",
            "Only the report subcommand can promote or block the matrix after every ensemble and comparison JSON exists.",
        ],
    }
    manifest_path.write_text(json.dumps(_json_clean(manifest), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    # Refresh the postprocess script after the manifest path exists.
    _write_script(postprocess_script, [*all_postprocess_commands, report_command], title="matched nonlinear transport matrix postprocess")
    return manifest


def _load_comparison(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def _maybe_float(value: Any) -> float | None:
    try:
        out = float(value)
    except (TypeError, ValueError):
        return None
    return out if math.isfinite(out) else None


def build_report(
    *,
    matrix_manifest: Path,
    min_pass_fraction: float,
    min_mean_relative_reduction: float,
) -> dict[str, Any]:
    manifest = _load_manifest(matrix_manifest)
    samples = manifest.get("samples")
    if not isinstance(samples, list):
        raise ValueError("matrix manifest is missing samples")
    rows: list[dict[str, Any]] = []
    missing: list[str] = []
    reductions: list[float] = []
    passed_count = 0
    for sample in samples:
        if not isinstance(sample, Mapping):
            continue
        comparison_info = sample.get("comparison")
        comparison_path = None
        if isinstance(comparison_info, Mapping):
            raw = comparison_info.get("json")
            comparison_path = ROOT / str(raw) if raw and not Path(str(raw)).is_absolute() else Path(str(raw or ""))
        if comparison_path is None or not comparison_path.exists():
            missing.append(str(sample.get("sample_id", "unknown")))
            rows.append(
                {
                    "sample_id": sample.get("sample_id"),
                    "surface_torflux": sample.get("surface_torflux"),
                    "alpha": sample.get("alpha"),
                    "ky": sample.get("ky"),
                    "passed": False,
                    "missing_comparison": True,
                    "comparison_json": _repo_relative(comparison_path) if comparison_path else None,
                }
            )
            continue
        comparison = _load_comparison(comparison_path)
        stats = comparison.get("statistics") if isinstance(comparison.get("statistics"), Mapping) else {}
        rel = _maybe_float(stats.get("relative_reduction"))
        z = _maybe_float(stats.get("uncertainty_z_score"))
        if rel is not None:
            reductions.append(rel)
        passed = bool(comparison.get("passed", False))
        passed_count += int(passed)
        rows.append(
            {
                "sample_id": sample.get("sample_id"),
                "surface_torflux": sample.get("surface_torflux"),
                "alpha": sample.get("alpha"),
                "ky": sample.get("ky"),
                "passed": passed,
                "missing_comparison": False,
                "comparison_json": _repo_relative(comparison_path),
                "relative_reduction": rel,
                "uncertainty_z_score": z,
                "baseline_mean": (comparison.get("baseline") or {}).get("ensemble_mean") if isinstance(comparison.get("baseline"), Mapping) else None,
                "candidate_mean": (comparison.get("candidate") or {}).get("ensemble_mean") if isinstance(comparison.get("candidate"), Mapping) else None,
            }
        )
    total = len(samples)
    pass_fraction = passed_count / total if total else 0.0
    mean_reduction = sum(reductions) / len(reductions) if reductions else None
    cfg = manifest.get("config") if isinstance(manifest.get("config"), Mapping) else {}
    surfaces = set(cfg.get("surfaces", [])) if isinstance(cfg.get("surfaces", []), list) else set()
    alphas = set(cfg.get("alphas", [])) if isinstance(cfg.get("alphas", []), list) else set()
    ky_values = set(cfg.get("ky_values", [])) if isinstance(cfg.get("ky_values", []), list) else set()
    blockers: list[str] = []
    if missing:
        blockers.append(f"missing comparisons: {', '.join(missing[:8])}{' ...' if len(missing) > 8 else ''}")
    if len(surfaces) < 3:
        blockers.append("coverage has fewer than three surfaces")
    if len(alphas) < 2:
        blockers.append("coverage has fewer than two field-line labels")
    if len(ky_values) < 3:
        blockers.append("coverage has fewer than three ky values")
    if pass_fraction < float(min_pass_fraction):
        blockers.append(f"pass_fraction {pass_fraction:.6g} < {float(min_pass_fraction):.6g}")
    if mean_reduction is None or mean_reduction < float(min_mean_relative_reduction):
        blockers.append(
            "mean_relative_reduction "
            f"{('n/a' if mean_reduction is None else f'{mean_reduction:.6g}')} < {float(min_mean_relative_reduction):.6g}"
        )
    passed = not blockers
    return {
        "kind": "matched_nonlinear_transport_matrix_report",
        "claim_level": "multi_surface_alpha_ky_matched_transport_matrix_gate",
        "passed": bool(passed),
        "matrix_manifest": _repo_relative(matrix_manifest),
        "config": {
            "min_pass_fraction": float(min_pass_fraction),
            "min_mean_relative_reduction": float(min_mean_relative_reduction),
        },
        "summary": {
            "total_samples": total,
            "completed_samples": total - len(missing),
            "passed_samples": passed_count,
            "pass_fraction": pass_fraction,
            "mean_relative_reduction": mean_reduction,
            "min_relative_reduction": min(reductions) if reductions else None,
            "max_relative_reduction": max(reductions) if reductions else None,
            "surfaces": sorted(float(value) for value in surfaces),
            "alphas": sorted(float(value) for value in alphas),
            "ky_values": sorted(float(value) for value in ky_values),
        },
        "blockers": blockers,
        "rows": rows,
        "notes": [
            "This gate promotes only the selected matched baseline-vs-candidate matrix.",
            "It does not by itself validate universal nonlinear transport optimization across all stellarator classes.",
        ],
    }


def _write_report_figure(report: Mapping[str, Any], path: Path) -> None:
    rows = [row for row in report.get("rows", []) if isinstance(row, Mapping)]
    path.parent.mkdir(parents=True, exist_ok=True)
    set_plot_style()
    fig, ax = plt.subplots(figsize=(8.2, 4.8), constrained_layout=True)
    fig.patch.set_facecolor("white")
    ax.set_facecolor("white")
    finite_rows = [row for row in rows if _maybe_float(row.get("relative_reduction")) is not None]
    if finite_rows:
        xs = list(range(len(finite_rows)))
        reductions = [100.0 * float(row["relative_reduction"]) for row in finite_rows]
        colors = ["#0f766e" if bool(row.get("passed", False)) else "#b45309" for row in finite_rows]
        labels = [
            f"s={float(row['surface_torflux']):.2f}\nα={float(row['alpha']):.2f}\nky={float(row['ky']):.2f}"
            for row in finite_rows
        ]
        ax.bar(xs, reductions, color=colors, edgecolor="0.2", linewidth=0.5)
        ax.axhline(0.0, color="0.2", linewidth=0.8)
        ax.set_xticks(xs, labels, rotation=60, ha="right", fontsize=7)
        ax.set_ylabel("candidate heat-flux reduction (%)")
    else:
        ax.text(
            0.5,
            0.5,
            "No completed matched comparisons found",
            transform=ax.transAxes,
            ha="center",
            va="center",
            fontsize=12,
        )
        ax.set_xticks([])
    status = "passes" if bool(report.get("passed", False)) else "blocked"
    summary = report.get("summary") if isinstance(report.get("summary"), Mapping) else {}
    ax.set_title(
        "Matched nonlinear transport matrix: "
        f"{status} ({summary.get('passed_samples', 0)}/{summary.get('total_samples', 0)} samples)",
        pad=12,
    )
    ax.grid(axis="y", alpha=0.25)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def build_write_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    parser = subparsers.add_parser("write", help="write a matched nonlinear transport matrix campaign")
    parser.add_argument("--baseline-vmec-file", required=True, type=Path)
    parser.add_argument("--candidate-vmec-file", required=True, type=Path)
    parser.add_argument("--baseline-label", default="baseline")
    parser.add_argument("--candidate-label", default="candidate")
    parser.add_argument("--case-prefix", default="qa_nonlinear_matrix")
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument("--artifact-dir", type=Path)
    parser.add_argument("--surfaces", default=DEFAULT_SURFACES)
    parser.add_argument("--alphas", default=DEFAULT_ALPHAS)
    parser.add_argument("--ky-values", default=DEFAULT_KY_VALUES)
    parser.add_argument("--grid", default=DEFAULT_GRID)
    parser.add_argument("--horizons", default=DEFAULT_HORIZONS)
    parser.add_argument("--dt", type=float, default=0.05)
    parser.add_argument("--baseline-seed", type=int, default=22)
    parser.add_argument("--seed-variant", action="append", type=int, default=None)
    parser.add_argument("--dt-variant", action="append", type=float, default=None)
    parser.add_argument("--Nl", type=int, default=4)
    parser.add_argument("--Nm", type=int, default=8)
    parser.add_argument("--npol", type=float, default=1.0)
    parser.add_argument("--tprim", type=float, default=3.0)
    parser.add_argument("--fprim", type=float, default=1.0)
    parser.add_argument("--nu", type=float, default=0.01)
    parser.add_argument("--init-amp", type=float, default=1.0e-3)
    parser.add_argument("--y0", type=float, default=21.0)
    parser.add_argument("--Lx", type=float, default=62.8)
    parser.add_argument("--Ly", type=float, default=62.8)
    parser.add_argument("--sample-stride", type=int, default=50)
    parser.add_argument("--diagnostics-stride", type=int, default=50)
    parser.add_argument("--window-tmin", type=float, default=DEFAULT_WINDOW[0])
    parser.add_argument("--window-tmax", type=float, default=DEFAULT_WINDOW[1])
    parser.add_argument("--min-samples", type=int, default=200)
    parser.add_argument("--min-window-samples", type=int, default=80)
    parser.add_argument("--max-mean-rel-spread", type=float, default=0.15)
    parser.add_argument("--max-combined-sem-rel", type=float, default=0.25)
    parser.add_argument("--min-relative-reduction", type=float, default=0.02)
    parser.add_argument("--min-pass-fraction", type=float, default=1.0)
    parser.add_argument("--min-mean-relative-reduction", type=float, default=0.02)
    parser.add_argument(
        "--gpu-splits",
        type=int,
        default=1,
        help="Write final-horizon direct launch scripts split over this many DEVICE ids.",
    )
    parser.set_defaults(func=_cmd_write)


def build_report_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    parser = subparsers.add_parser("report", help="aggregate a completed matched nonlinear transport matrix")
    parser.add_argument("--matrix-manifest", required=True, type=Path)
    parser.add_argument("--out-json", required=True, type=Path)
    parser.add_argument("--out-figure", type=Path)
    parser.add_argument("--min-pass-fraction", type=float, default=1.0)
    parser.add_argument("--min-mean-relative-reduction", type=float, default=0.02)
    parser.add_argument("--fail-on-blocked", action="store_true")
    parser.set_defaults(func=_cmd_report)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    build_write_parser(subparsers)
    build_report_parser(subparsers)
    return parser


def _cmd_write(args: argparse.Namespace) -> int:
    manifest = build_campaign(args)
    print(
        json.dumps(
            {
                "sample_count": manifest["config"]["sample_count"],
                "coverage_passed": manifest["coverage_gate"]["passed"],
                "manifest": _repo_relative(Path(args.out_dir) / "matched_transport_matrix_manifest.json"),
                "staged_script": manifest["launch_scripts"]["staged_ladder_skip_existing"],
                "final_horizon_script": manifest["launch_scripts"]["final_horizon_direct_skip_existing"],
                "postprocess_script": manifest["launch_scripts"]["postprocess"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


def _cmd_report(args: argparse.Namespace) -> int:
    report = build_report(
        matrix_manifest=args.matrix_manifest,
        min_pass_fraction=float(args.min_pass_fraction),
        min_mean_relative_reduction=float(args.min_mean_relative_reduction),
    )
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(_json_clean(report), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if args.out_figure is not None:
        _write_report_figure(report, args.out_figure)
    print(json.dumps({"passed": report["passed"], "summary": report["summary"], "blockers": report["blockers"]}, indent=2, sort_keys=True))
    if args.fail_on_blocked and not bool(report["passed"]):
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
