#!/usr/bin/env python3
"""Build a quasilinear calibration/holdout report from JSON points."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from spectraxgk.quasilinear_calibration import (
    calibration_point_from_spectrum_and_nonlinear_window,
    quasilinear_calibration_report,
    write_quasilinear_calibration_report,
)


def _load_points(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict) and "points" in data:
        data = data["points"]
    if not isinstance(data, list):
        raise TypeError("input JSON must be a list of calibration points or an object with a 'points' list")
    return [dict(item) for item in data]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--points", help="JSON list of calibration points")
    parser.add_argument("--spectrum", help="Quasilinear spectrum CSV for one generated point")
    parser.add_argument("--nonlinear-summary", help="Nonlinear window summary JSON for one generated point")
    parser.add_argument("--split", default="audit", help="train, holdout, or audit for generated point")
    parser.add_argument("--case", default=None, help="Optional case label for generated point")
    parser.add_argument("--geometry", default="unspecified", help="Geometry label for generated point")
    parser.add_argument("--electron-model", default="unspecified", help="Electron model label for generated point")
    parser.add_argument("--spectrum-column", default="saturated_heat_flux_total")
    parser.add_argument("--spectrum-method", default="sum", help="sum, mean, or trapezoid")
    parser.add_argument("--out", required=True, help="Output calibration report JSON")
    parser.add_argument("--saturation-rule", default="mixing_length")
    parser.add_argument("--holdout-mean-rel-gate", type=float, default=0.35)
    parser.add_argument("--observed-floor", type=float, default=1.0e-12)
    parser.add_argument(
        "--fit-train-scale",
        action="store_true",
        help="Fit one multiplicative heat-flux scale from train points before scoring holdout points.",
    )
    parser.add_argument("--version", default="0.1")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    points = []
    if args.points is not None:
        points.extend(_load_points(Path(args.points)))
    if args.spectrum is not None or args.nonlinear_summary is not None:
        if args.spectrum is None or args.nonlinear_summary is None:
            raise ValueError("--spectrum and --nonlinear-summary must be supplied together")
        points.append(
            calibration_point_from_spectrum_and_nonlinear_window(
                args.spectrum,
                args.nonlinear_summary,
                split=args.split,
                saturation_rule=args.saturation_rule,
                spectrum_column=args.spectrum_column,
                spectrum_method=args.spectrum_method,
                case=args.case,
                geometry=args.geometry,
                electron_model=args.electron_model,
                notes="generated by build_quasilinear_calibration_report.py",
            ).to_dict()
        )
    if not points:
        raise ValueError("provide --points or --spectrum plus --nonlinear-summary")
    report = quasilinear_calibration_report(
        points,
        saturation_rule=args.saturation_rule,
        version=args.version,
        holdout_mean_rel_gate=args.holdout_mean_rel_gate,
        observed_floor=args.observed_floor,
        fit_train_scale=args.fit_train_scale,
        metadata={
            "source_points": None if args.points is None else str(Path(args.points)),
            "source_spectrum": args.spectrum,
            "source_nonlinear_summary": args.nonlinear_summary,
        },
    )
    out = write_quasilinear_calibration_report(args.out, report)
    print(f"saved {out}")
    print(f"claim_level={report['claim_level']} passed={report['passed']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
