#!/usr/bin/env python3
"""Import a passed nonlinear transport matrix portfolio into docs artifacts.

This is intentionally fail-closed: a blocked or malformed portfolio is not a
release artifact. The tool only copies the canonical portfolio JSON/figure and
the selected family matrix report/figure after the portfolio gate has passed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DOCS_STATIC = ROOT / "docs" / "_static"


def _repo_relative(path: Path | str) -> str:
    raw = Path(path)
    try:
        return raw.resolve().relative_to(ROOT.resolve()).as_posix()
    except (OSError, ValueError):
        return raw.as_posix()


def _load_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def _parse_labeled_path(raw: str) -> tuple[str, Path]:
    if "=" not in raw:
        raise ValueError(f"expected LABEL=PATH, got {raw!r}")
    label, path = raw.split("=", 1)
    label = label.strip()
    if not label:
        raise ValueError(f"empty label in {raw!r}")
    return label, Path(path)


def _copy_required(src: Path, dst: Path) -> dict[str, str]:
    if not src.exists():
        raise FileNotFoundError(f"required artifact does not exist: {src}")
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return {"source": _repo_relative(src), "destination": _repo_relative(dst)}


def _copy_optional(src: Path | None, dst: Path) -> dict[str, str] | None:
    if src is None:
        return None
    return _copy_required(src, dst)


def import_artifacts(
    *,
    portfolio_json: Path,
    portfolio_figure: Path | None,
    matrix_report_jsons: dict[str, Path],
    matrix_report_figures: dict[str, Path],
    docs_static: Path = DEFAULT_DOCS_STATIC,
) -> dict[str, Any]:
    payload = _load_json(portfolio_json)
    if payload.get("kind") != "nonlinear_transport_matrix_portfolio_gate":
        raise ValueError("portfolio JSON is not a nonlinear transport matrix portfolio gate")
    if not bool(payload.get("passed", False)):
        raise ValueError("refusing to import a blocked nonlinear transport matrix portfolio")

    selected = payload.get("selected_family")
    if not isinstance(selected, str) or not selected:
        raise ValueError("passed portfolio does not record selected_family")
    if selected not in matrix_report_jsons:
        raise ValueError(f"missing selected matrix report JSON for {selected!r}")
    if selected not in matrix_report_figures:
        raise ValueError(f"missing selected matrix report figure for {selected!r}")

    copied: dict[str, Any] = {
        "portfolio_json": _copy_required(
            portfolio_json,
            docs_static / "nonlinear_transport_matrix_portfolio.json",
        ),
        "portfolio_figure": _copy_optional(
            portfolio_figure,
            docs_static / "nonlinear_transport_matrix_portfolio.png",
        ),
        "selected_family": selected,
        "selected_matrix_report_json": _copy_required(
            matrix_report_jsons[selected],
            docs_static / f"{selected}_matrix_report.json",
        ),
        "selected_matrix_report_figure": _copy_required(
            matrix_report_figures[selected],
            docs_static / f"{selected}_matrix_report.png",
        ),
    }
    manifest = {
        "kind": "nonlinear_transport_matrix_portfolio_import",
        "passed": True,
        "selected_family": selected,
        "copied": copied,
        "notes": [
            "Generated by tools/import_nonlinear_transport_matrix_portfolio.py.",
            "The import is fail-closed and requires a passing portfolio gate.",
        ],
    }
    (docs_static / "nonlinear_transport_matrix_portfolio_import.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--portfolio-json", required=True, type=Path)
    parser.add_argument("--portfolio-figure", type=Path)
    parser.add_argument(
        "--matrix-report-json",
        action="append",
        default=[],
        metavar="LABEL=PATH",
        help="Matrix report JSON keyed by candidate family label.",
    )
    parser.add_argument(
        "--matrix-report-figure",
        action="append",
        default=[],
        metavar="LABEL=PATH",
        help="Matrix report figure keyed by candidate family label.",
    )
    parser.add_argument("--docs-static", default=DEFAULT_DOCS_STATIC, type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    manifest = import_artifacts(
        portfolio_json=args.portfolio_json,
        portfolio_figure=args.portfolio_figure,
        matrix_report_jsons=dict(_parse_labeled_path(raw) for raw in args.matrix_report_json),
        matrix_report_figures=dict(_parse_labeled_path(raw) for raw in args.matrix_report_figure),
        docs_static=args.docs_static,
    )
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
