#!/usr/bin/env python3
"""Finalize release docs after a broad nonlinear transport matrix passes.

The script is a fail-closed wrapper around the nonlinear transport portfolio
importer and the readiness dashboards. It should be run only after
``tools/release/check_nonlinear_transport_matrix_portfolio.py`` has produced a passing
portfolio JSON.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DOCS_STATIC = ROOT / "docs" / "_static"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.artifacts import build_manuscript_readiness_status as manuscript_status  # noqa: E402
from tools.artifacts import build_pre_manuscript_closure_status as closure_status  # noqa: E402


def _repo_relative(path: Path | str) -> str:
    raw = Path(path)
    try:
        return raw.resolve().relative_to(ROOT.resolve()).as_posix()
    except (OSError, ValueError):
        return raw.as_posix()


def _parse_labeled_path(raw: str) -> tuple[str, Path]:
    if "=" not in raw:
        raise ValueError(f"expected LABEL=PATH, got {raw!r}")
    label, path = raw.split("=", 1)
    label = label.strip()
    if not label:
        raise ValueError(f"empty label in {raw!r}")
    return label, Path(path)


def _load_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def _copy_required(src: Path, dst: Path) -> dict[str, str]:
    if not src.exists():
        raise FileNotFoundError(f"required artifact does not exist: {src}")
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return {"source": _repo_relative(src), "destination": _repo_relative(dst)}


def _copy_optional(src: Path | None, dst: Path) -> dict[str, str] | None:
    if src is None:
        return None
    return _copy_required(src, dst)


def import_artifacts(
    *,
    portfolio_json: Path,
    portfolio_figure: Path | None,
    matrix_report_jsons: dict[str, Path],
    matrix_report_figures: dict[str, Path],
    docs_static: Path = DEFAULT_DOCS_STATIC,
) -> dict[str, Any]:
    """Import a passing matrix portfolio and its selected family artifacts."""

    payload = _load_json(portfolio_json)
    if payload.get("kind") != "nonlinear_transport_matrix_portfolio_gate":
        raise ValueError(
            "portfolio JSON is not a nonlinear transport matrix portfolio gate"
        )
    if not bool(payload.get("passed", False)):
        raise ValueError(
            "refusing to import a blocked nonlinear transport matrix portfolio"
        )

    selected = payload.get("selected_family")
    if not isinstance(selected, str) or not selected:
        raise ValueError("passed portfolio does not record selected_family")
    if selected not in matrix_report_jsons:
        raise ValueError(f"missing selected matrix report JSON for {selected!r}")
    if selected not in matrix_report_figures:
        raise ValueError(f"missing selected matrix report figure for {selected!r}")

    copied: dict[str, Any] = {
        "portfolio_json": _copy_required(
            portfolio_json,
            docs_static / "nonlinear_transport_matrix_portfolio.json",
        ),
        "portfolio_figure": _copy_optional(
            portfolio_figure,
            docs_static / "nonlinear_transport_matrix_portfolio.png",
        ),
        "selected_family": selected,
        "selected_matrix_report_json": _copy_required(
            matrix_report_jsons[selected],
            docs_static / f"{selected}_matrix_report.json",
        ),
        "selected_matrix_report_figure": _copy_required(
            matrix_report_figures[selected],
            docs_static / f"{selected}_matrix_report.png",
        ),
    }
    manifest = {
        "kind": "nonlinear_transport_matrix_portfolio_import",
        "passed": True,
        "selected_family": selected,
        "copied": copied,
        "notes": [
            "Generated by tools/campaigns/finalize_nonlinear_transport_matrix_release.py.",
            "The import is fail-closed and requires a passing portfolio gate.",
        ],
    }
    (docs_static / "nonlinear_transport_matrix_portfolio_import.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest


def finalize_release_artifacts(
    *,
    portfolio_json: Path,
    portfolio_figure: Path | None,
    matrix_report_jsons: dict[str, Path],
    matrix_report_figures: dict[str, Path],
    docs_static: Path = DEFAULT_DOCS_STATIC,
    regenerate_dashboards: bool = True,
) -> dict[str, Any]:
    """Import passing matrix artifacts and optionally rebuild status panels."""

    import_manifest = import_artifacts(
        portfolio_json=portfolio_json,
        portfolio_figure=portfolio_figure,
        matrix_report_jsons=matrix_report_jsons,
        matrix_report_figures=matrix_report_figures,
        docs_static=docs_static,
    )
    dashboards: dict[str, Any] = {}
    if regenerate_dashboards:
        root = docs_static.parent.parent
        manuscript_payload = manuscript_status.build_manuscript_readiness_payload(root)
        dashboards["manuscript_readiness_status"] = (
            manuscript_status.write_manuscript_readiness_artifacts(
                manuscript_payload,
                out=docs_static / "manuscript_readiness_status.png",
            )
        )
        closure_payload = closure_status.build_status_payload(root)
        dashboards["pre_manuscript_closure_status"] = (
            closure_status.write_status_artifacts(
                closure_payload,
                out=docs_static / "pre_manuscript_closure_status.png",
            )
        )
        runbook_payload = closure_status.build_runbook_payload(
            inventory_path=docs_static / "vmec_jax_equilibrium_inventory.json",
            screen_path=docs_static / "external_vmec_candidate_linear_screen.csv",
            external_runbook_path=docs_static
            / "external_vmec_next_holdout_runbook.json",
            holdout_gap_path=None,
            optimizer_manifest_path=docs_static
            / "vmec_jax_qa_optimizer_comparison_manifest.json",
            ladder_status_path=docs_static
            / "vmec_jax_qa_optimizer_ladder_resume_status.json",
            office_root=Path(
                "/home/rjorge/spectrax_optimizer_ladder_20260609/SPECTRAX-GK"
            ),
            audit_root=Path("tools_out/pre_manuscript_nonlinear_audits"),
        )
        dashboards["pre_manuscript_closure_runbook"] = (
            closure_status.write_runbook_artifacts(
                runbook_payload,
                out=docs_static / "pre_manuscript_closure_runbook.png",
            )
        )

    manifest = {
        "kind": "nonlinear_transport_matrix_release_finalization",
        "passed": True,
        "selected_family": import_manifest["selected_family"],
        "import_manifest": _repo_relative(
            docs_static / "nonlinear_transport_matrix_portfolio_import.json"
        ),
        "dashboards_regenerated": bool(regenerate_dashboards),
        "dashboards": dashboards,
        "notes": [
            "This release finalizer is fail-closed through its portfolio import gate.",
            "Strict t=1500 growth/QL/nonlinear-window rows remain excluded evidence.",
        ],
    }
    out = docs_static / "nonlinear_transport_matrix_release_finalization.json"
    out.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--portfolio-json", required=True, type=Path)
    parser.add_argument("--portfolio-figure", type=Path)
    parser.add_argument(
        "--matrix-report-json",
        action="append",
        default=[],
        metavar="LABEL=PATH",
        help="Matrix report JSON keyed by candidate family label.",
    )
    parser.add_argument(
        "--matrix-report-figure",
        action="append",
        default=[],
        metavar="LABEL=PATH",
        help="Matrix report figure keyed by candidate family label.",
    )
    parser.add_argument("--docs-static", default=DEFAULT_DOCS_STATIC, type=Path)
    parser.add_argument(
        "--skip-dashboard-regeneration",
        action="store_true",
        help="Import only. Intended for tests, not the release path.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    manifest = finalize_release_artifacts(
        portfolio_json=args.portfolio_json,
        portfolio_figure=args.portfolio_figure,
        matrix_report_jsons=dict(
            _parse_labeled_path(raw) for raw in args.matrix_report_json
        ),
        matrix_report_figures=dict(
            _parse_labeled_path(raw) for raw in args.matrix_report_figure
        ),
        docs_static=args.docs_static,
        regenerate_dashboards=not bool(args.skip_dashboard_regeneration),
    )
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
